"""Case = unit of investigation. Multiple alerts can roll up into one case."""
from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Optional
from sqlmodel import Field, SQLModel, JSON, Column


class CaseStatus(str, Enum):
    NEW = "new"
    TRIAGING = "triaging"
    INVESTIGATING = "investigating"
    AWAITING_HITL = "awaiting_hitl"
    RESPONDING = "responding"
    CLOSED_TRUE_POSITIVE = "closed_true_positive"
    CLOSED_FALSE_POSITIVE = "closed_false_positive"
    CLOSED_BENIGN = "closed_benign"
    ESCALATED = "escalated"


class Severity(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class Verdict(str, Enum):
    UNKNOWN = "unknown"
    TRUE_POSITIVE = "true_positive"
    FALSE_POSITIVE = "false_positive"
    BENIGN = "benign"
    NEEDS_HUMAN = "needs_human"


class Case(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    tenant_id: str = Field(default="demo-tenant", index=True)
    title: str
    narrative: str = ""  # auto-generated by Reporter
    status: CaseStatus = Field(default=CaseStatus.NEW, index=True)
    severity: Severity = Field(default=Severity.MEDIUM, index=True)
    verdict: Verdict = Field(default=Verdict.UNKNOWN)
    confidence: float = 0.0  # 0..1
    assignee: str | None = None
    mitre_techniques: list[str] = Field(default_factory=list, sa_column=Column(JSON))
    affected_users: list[str] = Field(default_factory=list, sa_column=Column(JSON))
    affected_hosts: list[str] = Field(default_factory=list, sa_column=Column(JSON))
    iocs: list[str] = Field(default_factory=list, sa_column=Column(JSON))
    response_actions: list[dict] = Field(default_factory=list, sa_column=Column(JSON))
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), index=True)
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    closed_at: datetime | None = None
