"""Marketplace endpoints — browse and install AiSOC marketplace items.

The marketplace ships as a single static index (``marketplace/index.json``)
generated by ``scripts/build_marketplace.py`` from the on-disk
``detections/``, ``playbooks/``, and ``plugins/`` trees.

This module provides a thin HTTP surface so the web UI can:

- Read the index server-side (``GET /v1/marketplace``)
- Filter by MITRE ATT&CK technique (``GET /v1/marketplace?mitre=T1078``)
- Install an item to the active tenant
  (``POST /v1/marketplace/install`` body=``{type,id}``)
- Read which items are currently installed for the tenant
  (``GET /v1/marketplace/installed``)

Install state is intentionally tracked in-memory per process for now —
the marketplace UI's “✓ Installed” affordance is the main consumer, and a
heavier per-tenant ``installed_items`` table can replace this without an
API contract change. The ``content_sha256`` field returned at install time
gives the UI something stable to display and lets us evolve to a DB-backed
store later.
"""

from __future__ import annotations

import hashlib
import json
import threading
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Literal

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel, Field

from app.api.v1.deps import AuthUser

router = APIRouter(prefix="/marketplace", tags=["marketplace"])

# ── Locating the on-disk index ────────────────────────────────────────────────

# On the host this file lives at services/api/app/api/v1/endpoints/marketplace.py
# so the repo root is six levels up. Inside the API Docker image only the
# /app/app/... subtree is copied, so parents[6] would IndexError. We resolve
# the deepest available ancestor and rely on the absolute container paths
# below as a safety net.
_HERE = Path(__file__).resolve()
_HERE_PARENTS = list(_HERE.parents)
_REPO_ROOT = _HERE_PARENTS[6] if len(_HERE_PARENTS) > 6 else _HERE_PARENTS[-1]
_CANDIDATE_PATHS = [
    _REPO_ROOT / "marketplace" / "index.json",
    _REPO_ROOT / "apps" / "web" / "public" / "marketplace" / "index.json",
    Path("/app/marketplace/index.json"),
    Path("/app/apps/web/public/marketplace/index.json"),
]


def _resolve_index_path() -> Path:
    for p in _CANDIDATE_PATHS:
        if p.exists():
            return p
    raise HTTPException(
        status_code=503,
        detail=("marketplace/index.json not found. Run `pnpm marketplace:build` to generate it."),
    )


_index_cache: dict[str, Any] = {"path": None, "mtime": 0.0, "data": None}
_index_lock = threading.Lock()


def _load_index() -> dict[str, Any]:
    """Load (and lazily refresh) the on-disk marketplace index."""
    path = _resolve_index_path()
    mtime = path.stat().st_mtime
    with _index_lock:
        if _index_cache["data"] is None or _index_cache["path"] != str(path) or _index_cache["mtime"] != mtime:
            try:
                _index_cache["data"] = json.loads(path.read_text(encoding="utf-8"))
            except Exception as exc:
                raise HTTPException(
                    status_code=500,
                    detail=f"Failed to parse marketplace index: {exc}",
                ) from exc
            _index_cache["path"] = str(path)
            _index_cache["mtime"] = mtime
        return _index_cache["data"]


# ── Per-tenant installed state ────────────────────────────────────────────────

# Keyed by (tenant_id, type, item_id) → install record. Replace with a real
# table when we move installed-set tracking into Postgres.
_installed: dict[tuple[str, str, str], dict[str, Any]] = {}
_installed_lock = threading.Lock()


def _install_record(
    tenant_id: str,
    item: dict[str, Any],
    sha256: str,
    user_email: str,
) -> dict[str, Any]:
    return {
        "id": item["id"],
        "type": item["type"],
        "name": item.get("name", item["id"]),
        "version": item.get("version", "1.0.0"),
        "path": item.get("path"),
        "content_sha256": sha256,
        "installed_at": datetime.now(UTC).isoformat(),
        "installed_by": user_email,
        "tenant_id": tenant_id,
    }


def _resolve_item_path(item: dict[str, Any]) -> Path:
    """Resolve a marketplace item's on-disk path safely.

    The ``rel`` value comes from ``marketplace/index.json``, which is
    generated by ``scripts/build_marketplace.py`` and *should* only ever
    contain relative paths inside ``detections/``, ``playbooks/``, or
    ``plugins/``. We still validate defensively so a tampered or
    misgenerated index can't be used to read arbitrary files via
    ``../../etc/passwd`` style entries.
    """
    rel = item.get("path")
    if not rel or not isinstance(rel, str):
        raise HTTPException(
            status_code=500,
            detail=f"Marketplace item {item.get('id')} has no path field",
        )

    rel_path = Path(rel)
    if rel_path.is_absolute() or any(part == ".." for part in rel_path.parts):
        # Either an absolute path or one with parent-directory traversal —
        # neither is ever legitimate for an index entry.
        raise HTTPException(
            status_code=400,
            detail="Invalid marketplace item path",
        )

    # Items must live under one of these trees. Anything else is rejected,
    # even if it resolves to a real file on disk.
    _ALLOWED_SUBDIRS = ("detections", "playbooks", "plugins")
    if rel_path.parts and rel_path.parts[0] not in _ALLOWED_SUBDIRS:
        raise HTTPException(
            status_code=400,
            detail="Marketplace items must live under detections/, playbooks/, or plugins/",
        )

    def _is_within(child: Path, parent: Path) -> bool:
        try:
            child.relative_to(parent)
        except ValueError:
            return False
        return True

    candidate_roots = [_REPO_ROOT, Path("/app")]
    for root in candidate_roots:
        resolved_root = root.resolve()
        target = (root / rel_path).resolve()
        if not _is_within(target, resolved_root):
            # Symlink games or odd resolution — refuse to serve.
            continue
        if target.exists():
            return target

    raise HTTPException(
        status_code=404,
        detail=f"Marketplace item file missing on disk: {rel}",
    )


def _hash_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


# ── Schemas ───────────────────────────────────────────────────────────────────


class InstallRequest(BaseModel):
    type: Literal["detection", "playbook", "plugin"]
    id: str = Field(..., min_length=1, max_length=200)


class InstallResponse(BaseModel):
    id: str
    type: str
    name: str
    version: str
    content_sha256: str
    installed_at: str
    installed_by: str
    already_installed: bool = False


class MarketplaceItemSummary(BaseModel):
    id: str
    type: str
    name: str
    description: str = ""
    version: str = "1.0.0"
    severity: str | None = None
    category: str | None = None
    source: str = "core"
    verified: bool = False
    sdks: list[str] = []
    mitre_techniques: list[str] = []
    tags: list[str] = []


class MarketplaceListResponse(BaseModel):
    total: int
    stats: dict[str, Any]
    mitre_coverage: dict[str, Any]
    items: list[MarketplaceItemSummary]
    installed_ids: list[str]


# ── Endpoints ─────────────────────────────────────────────────────────────────


@router.get("", response_model=MarketplaceListResponse)
async def list_marketplace(
    current_user: AuthUser,
    type_filter: Literal["detection", "playbook", "plugin"] | None = Query(None, alias="type"),
    mitre: str | None = Query(
        None,
        description="MITRE ATT&CK technique ID, e.g. T1078 or T1078.004",
    ),
    severity: str | None = Query(None),
    category: str | None = Query(None),
    source: Literal["core", "community"] | None = Query(None),
    sdk: Literal["python", "go", "both"] | None = Query(None),
    search: str | None = Query(None, max_length=200),
) -> MarketplaceListResponse:
    """Return the marketplace index with the same filters the UI exposes."""
    idx = _load_index()
    items: list[dict[str, Any]] = list(idx.get("items") or [])

    if type_filter:
        items = [i for i in items if i.get("type") == type_filter]
    if severity:
        items = [i for i in items if i.get("severity") == severity]
    if category:
        items = [i for i in items if i.get("category") == category]
    if source:
        items = [i for i in items if (i.get("source") or "core") == source]
    if mitre:
        mid = mitre.upper()
        items = [i for i in items if mid in (i.get("mitre_techniques") or [])]
    if sdk:
        kept: list[dict[str, Any]] = []
        for it in items:
            if it.get("type") != "plugin":
                continue
            sdks = it.get("sdks") or []
            if sdk == "both" and not ("python" in sdks and "go" in sdks):
                continue
            if sdk in ("python", "go") and sdk not in sdks:
                continue
            kept.append(it)
        items = kept
    if search:
        q = search.lower()
        items = [
            i
            for i in items
            if q in (i.get("name") or "").lower()
            or q in (i.get("description") or "").lower()
            or any(q in (t or "").lower() for t in (i.get("tags") or []))
            or any(q in (m or "").lower() for m in (i.get("mitre_techniques") or []))
            or q in (i.get("id") or "").lower()
        ]

    tenant_id = str(current_user.tenant_id)
    with _installed_lock:
        installed_ids = [key[2] for key in _installed if key[0] == tenant_id]

    return MarketplaceListResponse(
        total=len(items),
        stats=idx.get("stats") or {},
        mitre_coverage=idx.get("mitre_coverage") or {},
        items=[MarketplaceItemSummary(**_summarise(i)) for i in items],
        installed_ids=installed_ids,
    )


def _summarise(i: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": i.get("id", ""),
        "type": i.get("type", "detection"),
        "name": i.get("name") or i.get("id", ""),
        "description": (i.get("description") or "").strip(),
        "version": i.get("version", "1.0.0"),
        "severity": i.get("severity"),
        "category": i.get("category"),
        "source": i.get("source") or "core",
        "verified": bool(i.get("verified")),
        "sdks": list(i.get("sdks") or []),
        "mitre_techniques": list(i.get("mitre_techniques") or []),
        "tags": list(i.get("tags") or []),
    }


@router.post("/install", response_model=InstallResponse)
async def install_marketplace_item(
    body: InstallRequest,
    current_user: AuthUser,
) -> InstallResponse:
    """Activate a marketplace item for the caller's tenant.

    For core (on-disk) items this records that the item is "enabled"
    for the tenant — the underlying detection/playbook/plugin file is
    already present on the AiSOC instance and is read straight from disk
    by the relevant subsystem. The install marker is what the UI needs
    in order to show ``✓ Installed`` and what tenants can later disable.
    """
    idx = _load_index()
    match: dict[str, Any] | None = None
    for it in idx.get("items") or []:
        if it.get("type") == body.type and it.get("id") == body.id:
            match = it
            break
    if not match:
        raise HTTPException(
            status_code=404,
            detail=f"Marketplace item not found: {body.type}:{body.id}",
        )

    target = _resolve_item_path(match)
    sha = _hash_file(target)

    tenant_id = str(current_user.tenant_id)
    key = (tenant_id, body.type, body.id)
    user_email = current_user.email or str(current_user.user_id)

    with _installed_lock:
        existing = _installed.get(key)
        if existing:
            # Idempotent: re-installing returns the existing record but
            # refreshes the sha (e.g. file edited since last install).
            existing["content_sha256"] = sha
            existing["installed_at"] = datetime.now(UTC).isoformat()
            return InstallResponse(
                id=existing["id"],
                type=existing["type"],
                name=existing["name"],
                version=existing["version"],
                content_sha256=existing["content_sha256"],
                installed_at=existing["installed_at"],
                installed_by=existing["installed_by"],
                already_installed=True,
            )
        record = _install_record(tenant_id, match, sha, user_email)
        _installed[key] = record

    return InstallResponse(
        id=record["id"],
        type=record["type"],
        name=record["name"],
        version=record["version"],
        content_sha256=record["content_sha256"],
        installed_at=record["installed_at"],
        installed_by=record["installed_by"],
        already_installed=False,
    )


@router.delete("/install")
async def uninstall_marketplace_item(
    type: Literal["detection", "playbook", "plugin"],
    id: str,
    current_user: AuthUser,
) -> dict[str, Any]:
    """Remove a previously installed marketplace item from the tenant."""
    tenant_id = str(current_user.tenant_id)
    key = (tenant_id, type, id)
    with _installed_lock:
        removed = _installed.pop(key, None)
    if removed is None:
        raise HTTPException(
            status_code=404,
            detail=f"Item not installed for this tenant: {type}:{id}",
        )
    return {"status": "uninstalled", "id": id, "type": type}


@router.get("/installed")
async def list_installed(
    current_user: AuthUser,
) -> dict[str, Any]:
    """List all marketplace items installed for the caller's tenant."""
    tenant_id = str(current_user.tenant_id)
    with _installed_lock:
        items = [v for k, v in _installed.items() if k[0] == tenant_id]
    items.sort(key=lambda r: (r["type"], r["id"]))
    return {"total": len(items), "items": items}


@router.get("/mitre")
async def mitre_coverage(
    current_user: AuthUser,
) -> dict[str, Any]:
    """Return the MITRE ATT&CK coverage block from the marketplace index.

    Useful for the marketplace UI to render its MITRE filter without
    walking every item on the client.
    """
    idx = _load_index()
    coverage = idx.get("mitre_coverage") or {
        "techniques": {},
        "unique_techniques": 0,
        "total_with_mitre": 0,
    }
    return coverage
