import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "category",
      label: "Getting Started",
      items: [
        "intro",
        "installation",
        "quickstart",
        "architecture",
        "benchmark",
        "benchmark-methodology",
        "benchmark-scoreboard",
      ],
    },
    {
      type: "category",
      label: "Core Concepts",
      items: [
        "concepts/capabilities",
        "concepts/cases",
        "concepts/playbooks",
        "concepts/detections",
        "concepts/live-actions",
        "concepts/automation-maturity",
        "concepts/self-play",
        "concepts/investigation-swarm",
        "concepts/compounding-memory",
        "concepts/model-router",
        "concepts/llmops",
      ],
    },
    {
      type: "category",
      label: "Features",
      items: [
        "features/connector-health",
        "features/data-pipeline",
        "features/attack-path-agent",
      ],
    },
    {
      type: "category",
      label: "Console",
      items: [
        "console/funnel-kpis",
        "console/queue",
        "console/rule-tuning",
        "console/investigation-rail",
        "console/public-replay",
      ],
    },
    {
      type: "category",
      label: "Architecture",
      items: [
        "architecture/overview",
        "architecture/agents",
        "architecture/graph-schema",
        "architecture/itsm-as-source-of-truth",
      ],
    },
    {
      type: "category",
      label: "Connectors",
      items: [
        "connectors/index",
        "connectors/hello-connector",
        "connectors/endpoint-decision-matrix",
        "connectors/api-coverage",
        "connectors/universal-capture",
        "connectors/azure-entra",
        "connectors/azure-activity",
        "connectors/azure-defender",
        "connectors/gcp-cloud-audit",
        "connectors/gcp-scc",
        "connectors/m365-audit",
        "connectors/google-workspace",
        "connectors/cloudflare",
        "connectors/github",
        "connectors/tailscale",
        "connectors/osctrl",
        "connectors/wazuh",
        "connectors/fleetdm",
        "connectors/osquery-extensions",
        "connectors/auditd",
        "connectors/wiz",
        "connectors/aws-security-hub",
        "connectors/lacework",
        "connectors/prisma-cloud",
        "connectors/orca",
        "connectors/aws-guardduty",
        "connectors/aws-cloudtrail",
        "connectors/aws-vpc-flow",
        "connectors/kubernetes-audit",
        "connectors/qradar",
        "connectors/exabeam",
        "connectors/securonix",
        "connectors/devo",
        "connectors/netskope",
        "connectors/windows_event",
        "connectors/zeek_suricata",
        "connectors/syslog_cef",
        "connectors/llm_usage",
      ],
    },
    {
      type: "category",
      label: "Detections",
      items: ["detections/coverage", "detections/hello-hunt"],
    },
    {
      type: "category",
      label: "Benchmarks",
      items: ["benchmarks/alert-reduction"],
    },
    {
      type: "category",
      label: "Operations",
      items: [
        "operations/security",
        "operations/credentials",
        "operations/secrets",
        "operations/airgap",
        "operations/air-gapped",
        "operations/llm-gateway",
        "operations/codespaces",
        "operations/theming",
        "operations/upgrades",
        "operations/notifications",
        "operations/case-reports",
        "operations/troubleshooting",
        "operations/faq",
        "operations/adoption-questions",
        "operations/managed-instance",
      ],
    },
    {
      type: "category",
      label: "Plugin SDK",
      items: [
        "plugins/overview",
        "plugins/python-sdk",
        "plugins/hello-plugin",
        "plugins/go-sdk",
        "plugins/publishing",
        "plugins/cli",
        "plugins/lifecycle",
      ],
    },
    {
      type: "category",
      label: "Integrations",
      items: ["integrations/mcp", "integrations/misp-push", "integrations/github-action"],
    },
    {
      type: "category",
      label: "API Reference",
      items: ["api/rest", "api/graphql", "api/websocket"],
    },
    {
      type: "category",
      label: "Deployment",
      items: [
        "deployment/docker",
        "deployment/kubernetes",
        "deployment/gcp",
        "deployment/azure",
        "deployment/env-vars",
      ],
    },
    {
      type: "category",
      label: "Contributing",
      items: ["contributing/dev-setup", "contributing/guidelines"],
    },
    "glossary",
  ],
};

export default sidebars;
