// AUTO-GENERATED by scripts/generate_connector_count.py.
// Do not edit by hand. Run the script (or `make connector-count`) instead.
//
// This module is the single source of truth for every prose claim of the
// form "N connectors" or "All N connectors" across the marketing site,
// docs portal, and pricing surfaces. The count itself comes from the
// _CONNECTOR_CLASSES tuple in services/connectors/app/connectors/__init__.py.

import data from './connector-count.json';

export const CONNECTOR_COUNT: number = data.count;
export const CONNECTOR_CATEGORIES: Readonly<Record<string, number>> = data.categories;

// Human-readable label used in marquees / chips.
export const CONNECTOR_COUNT_LABEL = `${CONNECTOR_COUNT} connectors`;
