"""
AiSOC WS-B4: Detection-as-Code git PR path — GitHub integration service.

Creates a GitHub Pull Request that commits a detection rule file into the
configured repository branch when a detection proposal is promoted.

All public entry-points are async and return ``None`` gracefully when GitHub
credentials are not configured, so callers can always await them without
guarding for missing config.
"""

from __future__ import annotations

import base64
import logging
import re
from typing import Any

import httpx

from app.core.config import Settings

logger = logging.getLogger(__name__)

_GITHUB_API = "https://api.github.com"
_DETECTION_LANGUAGE_EXT: dict[str, str] = {
    "sigma": "yml",
    "yara": "yar",
    "suricata": "rules",
    "kql": "kql",
    "spl": "spl",
    "lucene": "json",
}


def _slug(name: str) -> str:
    """Convert a human-readable rule name to a safe filename slug."""
    slug = name.lower().strip()
    slug = re.sub(r"[^a-z0-9]+", "_", slug)
    slug = slug.strip("_")
    return slug or "detection_rule"


def _safe_for_log(value: str, max_len: int = 120) -> str:
    """
    Sanitize a value before logging it.

    Strips CR/LF (preventing log-injection), removes other ASCII control
    characters, and truncates to ``max_len`` characters. CodeQL's
    ``py/log-injection`` rule recognises this explicit replace-and-truncate
    pattern as a sanitizer, even when callers have already validated the
    input upstream (e.g. UUID path params or repo-built filename slugs).
    """
    if value is None:
        return ""
    s = str(value).replace("\n", " ").replace("\r", " ").replace("\t", " ")
    # Strip remaining ASCII control characters (0x00–0x1F, 0x7F).
    s = re.sub(r"[\x00-\x1f\x7f]", "", s)
    if len(s) > max_len:
        s = s[:max_len] + "…"
    return s


def _ext(language: str) -> str:
    return _DETECTION_LANGUAGE_EXT.get(language.lower(), "txt")


def _is_configured(settings: Settings) -> bool:
    return bool(settings.AISOC_GITHUB_TOKEN and settings.AISOC_GITHUB_REPO and settings.AISOC_GITHUB_DETECTIONS_PATH)


async def create_detection_pr(
    *,
    settings: Settings,
    proposal_id: str,
    rule_name: str,
    rule_language: str,
    rule_body: str,
    category: str,
) -> str | None:
    """
    Commit a detection rule file to a new branch and open a Pull Request.

    Parameters
    ----------
    settings:       Application settings (reads AISOC_GITHUB_* vars).
    proposal_id:    UUID string of the promoted ``DetectionRuleProposal``.
    rule_name:      Human-readable name used for the filename and PR title.
    rule_language:  Detection language (sigma, yara, …).
    rule_body:      Raw rule content to commit.
    category:       Rule category used as a subdirectory within the detections
                    path (e.g. "endpoint", "network").

    Returns
    -------
    str | None
        The HTTPS URL of the newly created Pull Request, or ``None`` if GitHub
        integration is not configured or the API call fails.
    """
    if not _is_configured(settings):
        logger.debug("GitHub integration not configured — skipping PR creation.")
        return None

    token = settings.AISOC_GITHUB_TOKEN
    repo = settings.AISOC_GITHUB_REPO
    base_path = settings.AISOC_GITHUB_DETECTIONS_PATH.rstrip("/")
    slug = _slug(rule_name)
    ext = _ext(rule_language)
    short_id = proposal_id[:8]

    branch_name = f"detection/{slug}-{short_id}"
    file_path = f"{base_path}/{category}/{slug}.{ext}"
    commit_message = f"feat(detection): add {rule_name} [{short_id}]"
    pr_title = f"Detection: {rule_name}"
    pr_body = (
        f"**Proposal ID:** `{proposal_id}`\n\n"
        f"**Language:** {rule_language}\n"
        f"**Category:** {category}\n\n"
        f"This PR was auto-generated by AiSOC when proposal `{proposal_id}` "
        f"was promoted through the in-app Detection-as-Code editor. "
        f"Review the rule, run the eval harness, and merge when satisfied.\n\n"
        f"<!-- aisoc:proposal:{proposal_id} -->"
    )

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    async with httpx.AsyncClient(base_url=_GITHUB_API, timeout=30.0) as client:
        # 1. Resolve the default branch SHA.
        default_branch, base_sha = await _get_default_branch_and_sha(client, headers, repo)
        if not base_sha:
            return None

        # 2. Create branch from base SHA.
        created = await _create_branch(client, headers, repo, branch_name, base_sha)
        if not created:
            return None

        # 3. Commit the rule file.
        committed = await _commit_file(
            client,
            headers,
            repo,
            branch_name,
            file_path,
            rule_body,
            commit_message,
        )
        if not committed:
            return None

        # 4. Open the PR.
        pr_url = await _open_pr(
            client,
            headers,
            repo,
            pr_title,
            pr_body,
            branch_name,
            default_branch,
        )
        return pr_url


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------


async def _get_default_branch_and_sha(
    client: httpx.AsyncClient,
    headers: dict[str, str],
    repo: str,
) -> tuple[str, str | None]:
    try:
        resp = await client.get(f"/repos/{repo}", headers=headers)
        resp.raise_for_status()
        data: dict[str, Any] = resp.json()
        default_branch: str = data.get("default_branch", "main")

        ref_resp = await client.get(f"/repos/{repo}/git/ref/heads/{default_branch}", headers=headers)
        ref_resp.raise_for_status()
        sha: str = ref_resp.json()["object"]["sha"]
        return default_branch, sha
    except Exception as exc:
        logger.warning("GitHub: failed to resolve default branch SHA — %s", exc)
        return "main", None


async def _create_branch(
    client: httpx.AsyncClient,
    headers: dict[str, str],
    repo: str,
    branch_name: str,
    sha: str,
) -> bool:
    try:
        resp = await client.post(
            f"/repos/{repo}/git/refs",
            headers=headers,
            json={"ref": f"refs/heads/{branch_name}", "sha": sha},
        )
        if resp.status_code == 422:
            # Branch already exists — safe to continue.
            return True
        resp.raise_for_status()
        return True
    except Exception as exc:
        logger.warning(
            "GitHub: failed to create branch %s — %s",
            _safe_for_log(branch_name),
            type(exc).__name__,
        )
        return False


async def _commit_file(
    client: httpx.AsyncClient,
    headers: dict[str, str],
    repo: str,
    branch_name: str,
    file_path: str,
    content: str,
    message: str,
) -> bool:
    encoded = base64.b64encode(content.encode()).decode()
    payload: dict[str, Any] = {
        "message": message,
        "content": encoded,
        "branch": branch_name,
    }

    # Fetch existing file SHA if it exists (so GitHub accepts an update).
    try:
        existing = await client.get(
            f"/repos/{repo}/contents/{file_path}",
            headers=headers,
            params={"ref": branch_name},
        )
        if existing.status_code == 200:
            payload["sha"] = existing.json().get("sha")
    except Exception as exc:  # noqa: BLE001 — SHA fetch is best-effort; missing SHA just overwrites
        logger.debug(
            "GitHub: could not fetch existing SHA for %s: %s",
            _safe_for_log(file_path),
            type(exc).__name__,
        )

    try:
        resp = await client.put(
            f"/repos/{repo}/contents/{file_path}",
            headers=headers,
            json=payload,
        )
        resp.raise_for_status()
        return True
    except Exception as exc:
        logger.warning(
            "GitHub: failed to commit file %s — %s",
            _safe_for_log(file_path),
            type(exc).__name__,
        )
        return False


async def _open_pr(
    client: httpx.AsyncClient,
    headers: dict[str, str],
    repo: str,
    title: str,
    body: str,
    head: str,
    base: str,
) -> str | None:
    try:
        resp = await client.post(
            f"/repos/{repo}/pulls",
            headers=headers,
            json={
                "title": title,
                "body": body,
                "head": head,
                "base": base,
                "draft": True,
            },
        )
        if resp.status_code == 422:
            # PR already exists for this branch — try to find it.
            search = await client.get(
                f"/repos/{repo}/pulls",
                headers=headers,
                params={"head": f"{repo.split('/')[0]}:{head}", "state": "open"},
            )
            if search.status_code == 200 and search.json():
                return search.json()[0]["html_url"]
            return None
        resp.raise_for_status()
        return resp.json()["html_url"]
    except Exception as exc:
        logger.warning(
            "GitHub: failed to open PR for branch %s — %s",
            _safe_for_log(head),
            type(exc).__name__,
        )
        return None
