"""
Chapter 3: Existing System
Written in clear, simple, human-understandable academic language.
Explains how traditional SOCs work today, their limitations, alert fatigue, and why manual incident response fails.
"""
import os
from docx.shared import Inches

def generate_chapter_3(add_p, add_ch_heading, add_sec_heading, add_subsec_heading, add_code, add_table, add_fig, fig_dir):
    add_ch_heading("CHAPTER 3\nEXISTING SYSTEM")
    
    add_sec_heading("3.1 Overview of Traditional SOC Operations")
    add_p("In traditional enterprise security operations, organizations rely on a multi-tiered team of human analysts to review and respond to security alarms. The team is usually structured into three levels:")
    add_p("1. Tier-1 Analysts (Triage): Responsible for monitoring the incoming alert queue 24/7, filtering out obvious false alarms, and forwarding suspicious events to Tier-2.")
    add_p("2. Tier-2 Responders (Investigation): Perform in-depth investigation by querying database logs, checking infected computers, and executing containment steps.")
    add_p("3. Tier-3 Engineers and Leads (Threat Hunting & Governance): Specialize in advanced threat hunting, creating new detection rules, and handling major security crises.")
    add_p("When a firewall or antivirus program detects something suspicious, it generates an alert and places it into a central queue. A Tier-1 analyst opens the alert, manually copies IP addresses or usernames, and checks external websites (such as VirusTotal) to see if the activity is dangerous.")
    
    # Figure 3.1: Traditional SOC Funnel
    add_fig(os.path.join(fig_dir, "fig3_1_traditional_soc_funnel.png"), "Figure 3.1: Traditional Multi-Tier Security Triage Process and Hand-off Delays", 5.8)

    add_p("If the alert appears serious, the Tier-1 analyst writes notes and passes the ticket to a Tier-2 responder. The responder then opens separate management portals (such as the cloud dashboard or endpoint console) to isolate the device or reset the user's account.")
    add_p("Because every step requires manual human intervention and ticket hand-offs between different teams, a single alert often sits waiting for 15 to 45 minutes before anyone looks at it, and takes nearly an hour to resolve.")

    add_sec_heading("3.2 Key Weaknesses in the Existing System")
    add_p("Traditional security setups suffer from five major weaknesses:")
    add_p("1. Disconnected Tools and Information Silos: Security tools from different vendors do not talk to each other. An antivirus alarm on a laptop, a suspicious login in the cloud, and a firewall block are treated as three completely separate events, even if they were caused by the same attacker. The analyst has to manually connect the dots.")
    add_p("2. Rigid Keyword and Threshold Rules: Traditional systems rely on simple 'if-then' rules. For example, a rule might trigger if a user fails to log in 5 times in 1 minute. Attackers easily bypass these rules by slowing down their attempts or slightly altering their commands.")
    add_p("3. Overwhelming False Alarms: Over 80% of all security alerts generated by traditional tools turn out to be harmless routine activity. Spending hours checking false alarms causes extreme fatigue for human analysts.")
    add_p("4. Lack of Safety Controls in Automated Scripts: Early automation tools run rigid scripts without checking the context. If a script accidentally blocks an essential company database or the CEO's account, it disrupts normal business. Because of this risk, many companies disable automatic response entirely.")
    add_p("5. High Licensing Costs: Traditional commercial tools charge organizations based on the volume of data ingested (per Gigabyte). This forces companies to discard certain log files to save money, creating dangerous blind spots.")

    add_sec_heading("3.3 Comparison of Operational Metrics")
    table_ex_headers = ["Operational Metric", "Traditional Baseline", "Impact on Organization", "Root Cause"]
    table_ex_widths = [Inches(1.6), Inches(1.4), Inches(2.0), Inches(1.8)]
    table_ex_data = [
        ["Daily Alert Volume", "10,000 to 500,000", "Analysts cannot keep up with the queue.", "Lack of automatic deduplication and noise filtering."],
        ["False Alarm Rate", "80% to 90%", "Analysts get exhausted and miss real attacks.", "Simple signature rules that lack context."],
        ["Time to Acknowledge (MTTA)", "15 to 45 Minutes", "Critical attacks sit unnoticed in backlogs.", "Manual, ticket-by-ticket queue processing."],
        ["Time to Remediate (MTTR)", "45 to 60+ Minutes", "Attackers have time to steal data or encrypt files.", "Switching between 5 to 10 disconnected software tools."],
        ["Attacker Dwell Time", "16 to 200+ Days", "Attackers remain hidden inside the network.", "Lack of interconnected graph relationships across logs."],
        ["Analyst Job Turnover", "35% to 50% Annually", "High training costs and loss of experienced staff.", "Stress and burnout from repetitive, boring manual tasks."]
    ]
    add_table(table_ex_widths, table_ex_headers, table_ex_data, "Table 3.1: Comparison of Operational Performance Metrics in Traditional Manual SOC Environments")
    add_p("As summarized in Table 3.1, traditional SOC operations experience significant delays due to high false alarm rates and manual ticket hand-offs across multiple tools.")

    add_sec_heading("3.4 Disadvantages of the Existing System")
    add_p("In summary, the existing approach has four fundamental disadvantages:")
    add_p("• Poor Scalability: As a company grows and generates more logs, hiring more human analysts becomes too expensive and unsustainable.")
    add_p("• High Risk of Human Error: Fatigued analysts working long shifts can easily overlook subtle clues or make mistakes when typing commands.")
    add_p("• Slow Response Times: Manual ticket hand-offs give attackers the time they need to spread across multiple servers.")
    add_p("• Expensive Maintenance: Maintaining hundreds of rigid detection rules and linear playbooks requires constant manual effort.")

print("Chapter 3 rewritten in clear, understandable academic style.")
