"""
Detection Pack v1 - Part 3 / Cloud (150 new specs)
==================================================

Native cloud detection rules covering AWS, Azure, GCP, Kubernetes and a small
multi-cloud bucket. These extend the 40 stable cloud rules in `detection_specs.CLOUD`
to a total of 190 native cloud detections.

Authoring rules
---------------
*   Use the ``S()`` helper from ``detection_specs_part3_helpers`` so every spec
    auto-generates positive/negative fixtures from a flat ``match_when`` clause.
    For nested ``any_of`` / ``all_of`` clauses you must pass explicit fixtures.
*   Slugs prefixed with ``aws-``, ``azure-``, ``gcp-``, ``k8s-`` or ``cloud-``
    follow the convention used in ``detection_specs.CLOUD``. New slugs MUST NOT
    collide with existing ones.
*   Severity guidance:
    * critical : direct credential or data compromise / persistence with broad
      blast radius.
    * high     : strong indicator of a single-tenant attack technique.
    * medium   : posture / mis-configuration / suspicious-but-tunable behaviour.
    * low      : noisy or intel-only signals.
"""

from __future__ import annotations

from detection_specs_part3_helpers import (  # type: ignore[import-not-found]
    FP_AUTOMATION,
    FP_BACKUP,
    FP_BREAK_GLASS,
    FP_FORENSIC,
    FP_TUNING,
    S,
)

# ---------------------------------------------------------------------------
# AWS (60 rules)
# ---------------------------------------------------------------------------
AWS_RULES: list[dict] = [
    # ---- IAM (15) ----
    S(slug="aws-iam-attach-administrator-access", name="AWS IAM AdministratorAccess Policy Attached",
      severity="high", mitre=["t1078.004", "t1098"], product="aws", service="iam",
      when={"event_name_in": ["AttachUserPolicy", "AttachRolePolicy", "AttachGroupPolicy"],
            "policy_arn": "arn:aws:iam::aws:policy/AdministratorAccess"},
      fp=["IAM bootstrap during account vending", FP_AUTOMATION], playbook="tpl-privilege-escalation"),
    S(slug="aws-iam-key-rotation-skipped", name="AWS IAM Access Key Older Than 365 Days",
      severity="medium", mitre=["t1078.004"], product="aws", service="iam",
      when={"event_name": "ListAccessKeys", "key_age_days_gt": 365},
      fp=[FP_AUTOMATION, "Service-account key intentionally pinned"], playbook="tpl-credential-hygiene"),
    S(slug="aws-iam-mfa-disabled-on-priv-user", name="AWS IAM MFA Removed From Privileged User",
      severity="critical", mitre=["t1556.006"], product="aws", service="iam",
      when={"event_name": "DeactivateMFADevice", "target_user_priv": True},
      fp=[FP_BREAK_GLASS, "Token rotation procedure"], playbook="tpl-defense-evasion"),
    S(slug="aws-iam-role-trust-broadened-wildcard", name="AWS IAM Role Trust Policy Allows Principal '*'",
      severity="critical", mitre=["t1078.004", "t1098.001"], product="aws", service="iam",
      when={"event_name": "UpdateAssumeRolePolicy", "trust_principal": "*"},
      fp=["Sandbox / training account by design"], playbook="tpl-privilege-escalation"),
    S(slug="aws-iam-policy-version-set-default-broad", name="AWS IAM Policy Version Set With Wildcard Action",
      severity="high", mitre=["t1098"], product="aws", service="iam",
      when={"event_name": "SetDefaultPolicyVersion", "policy_action": "*", "policy_resource": "*"},
      fp=[FP_AUTOMATION], playbook="tpl-privilege-escalation"),
    S(slug="aws-iam-permissions-boundary-removed", name="AWS IAM Permissions Boundary Removed",
      severity="high", mitre=["t1098"], product="aws", service="iam",
      when={"event_name": "DeleteUserPermissionsBoundary"},
      fp=["Boundary refactor (tracked in change ticket)"], playbook="tpl-privilege-escalation"),
    S(slug="aws-iam-saml-provider-modified", name="AWS IAM SAML Provider Updated",
      severity="high", mitre=["t1556"], product="aws", service="iam",
      when={"event_name_in": ["UpdateSAMLProvider", "CreateSAMLProvider"]},
      fp=["IdP migration (must be ticketed)", FP_AUTOMATION], playbook="tpl-defense-evasion"),
    S(slug="aws-iam-cross-account-role-broad-trust", name="AWS IAM Role Trusts Foreign Account Root",
      severity="high", mitre=["t1199"], product="aws", service="iam",
      when={"event_name": "CreateRole", "trust_principal_endswith": ":root", "trust_principal_external": True},
      fp=["Approved partner integration"], playbook="tpl-initial-access"),
    S(slug="aws-iam-anonymous-role-trust", name="AWS IAM Role Trusts Anonymous Federation",
      severity="critical", mitre=["t1199"], product="aws", service="iam",
      when={"event_name": "CreateRole", "trust_principal_in": ["anonymous", "AllUsers"]},
      fp=[], playbook="tpl-initial-access"),
    S(slug="aws-iam-create-user-burst", name="AWS IAM CreateUser Burst",
      severity="medium", mitre=["t1136.003"], product="aws", service="iam",
      when={"event_name": "CreateUser", "events_per_minute_gt": 10},
      fp=["Bulk onboarding window", FP_AUTOMATION], playbook="tpl-persistence"),
    S(slug="aws-iam-account-summary-recon", name="AWS IAM GetAccountSummary Recon Burst",
      severity="low", mitre=["t1087.004"], product="aws", service="iam",
      when={"event_name_in": ["GetAccountSummary", "GetAccountAuthorizationDetails"], "events_per_minute_gt": 5},
      fp=["IAM Access Analyzer routine"], playbook="tpl-discovery"),
    S(slug="aws-iam-list-keys-recon", name="AWS IAM ListAccessKeys Recon Across Users",
      severity="medium", mitre=["t1087.004"], product="aws", service="iam",
      when={"event_name": "ListAccessKeys", "distinct_users_per_minute_gt": 20},
      fp=["Compliance audit job"], playbook="tpl-discovery"),
    S(slug="aws-iam-login-profile-created-existing-user", name="AWS IAM Login Profile Added To Existing User",
      severity="high", mitre=["t1098.001"], product="aws", service="iam",
      when={"event_name": "CreateLoginProfile", "user_existed": True},
      fp=["Migrating service account to interactive use"], playbook="tpl-persistence"),
    S(slug="aws-iam-access-key-created-other-user", name="AWS IAM Access Key Created For Another User",
      severity="high", mitre=["t1098.001"], product="aws", service="iam",
      when={"event_name": "CreateAccessKey", "actor_eq_target": False},
      fp=["Helpdesk ticket (must be linked)"], playbook="tpl-persistence"),
    S(slug="aws-iam-policy-with-notaction", name="AWS IAM Policy Created With NotAction Wildcard",
      severity="high", mitre=["t1098"], product="aws", service="iam",
      when={"event_name_in": ["CreatePolicy", "CreatePolicyVersion"], "policy_uses_notaction": True},
      fp=[FP_TUNING], playbook="tpl-privilege-escalation"),
    # ---- S3 / EBS (8) ----
    S(slug="aws-s3-block-public-access-disabled", name="AWS S3 Block Public Access Disabled",
      severity="critical", mitre=["t1530"], product="aws", service="s3",
      when={"event_name_in": ["PutBucketPublicAccessBlock", "DeletePublicAccessBlock"], "block_public_acls": False},
      fp=["Static site bucket explicitly public"], playbook="tpl-data-exposure"),
    S(slug="aws-s3-bucket-policy-allows-anonymous", name="AWS S3 Bucket Policy Allows Principal '*'",
      severity="critical", mitre=["t1530"], product="aws", service="s3",
      when={"event_name": "PutBucketPolicy", "policy_principal": "*"},
      fp=["Public download bucket (documented)"], playbook="tpl-data-exposure"),
    S(slug="aws-s3-replication-to-foreign-account", name="AWS S3 Replication Configured To External Account",
      severity="high", mitre=["t1537"], product="aws", service="s3",
      when={"event_name": "PutBucketReplication", "destination_account_external": True},
      fp=["Approved cross-account DR pipeline"], playbook="tpl-exfiltration"),
    S(slug="aws-s3-server-access-logging-disabled", name="AWS S3 Server Access Logging Disabled",
      severity="medium", mitre=["t1562.008"], product="aws", service="s3",
      when={"event_name": "PutBucketLogging", "logging_enabled": False},
      fp=[FP_AUTOMATION, "Decommissioned bucket"], playbook="tpl-defense-evasion"),
    S(slug="aws-s3-object-lock-disabled", name="AWS S3 Object Lock / Retention Disabled",
      severity="high", mitre=["t1485"], product="aws", service="s3",
      when={"event_name_in": ["PutObjectLockConfiguration", "PutObjectRetention"], "retention_disabled": True},
      fp=[FP_AUTOMATION], playbook="tpl-impact"),
    S(slug="aws-s3-mass-deleteobject", name="AWS S3 Mass DeleteObject Burst",
      severity="critical", mitre=["t1485"], product="aws", service="s3",
      when={"event_name": "DeleteObject", "objects_per_minute_gt": 1000},
      fp=["Lifecycle policy run", FP_BACKUP], playbook="tpl-impact"),
    S(slug="aws-ebs-snapshot-shared-foreign", name="AWS EBS Snapshot Shared With Foreign Account",
      severity="high", mitre=["t1537"], product="aws", service="ec2",
      when={"event_name": "ModifySnapshotAttribute", "shared_account_external": True},
      fp=["Approved DR copy"], playbook="tpl-exfiltration"),
    S(slug="aws-ami-shared-public", name="AWS AMI Shared Publicly",
      severity="high", mitre=["t1537"], product="aws", service="ec2",
      when={"event_name": "ModifyImageAttribute", "ami_made_public": True},
      fp=["Marketplace publishing workflow"], playbook="tpl-exfiltration"),
    # ---- EC2 / VPC (8) ----
    S(slug="aws-ec2-imds-v1-allowed", name="AWS EC2 Instance Launched With IMDSv1 Allowed",
      severity="medium", mitre=["t1552.005"], product="aws", service="ec2",
      when={"event_name": "RunInstances", "imds_v1_allowed": True},
      fp=["Legacy AMI (must be ticketed)"], playbook="tpl-credential-access"),
    S(slug="aws-ec2-key-pair-imported", name="AWS EC2 Key Pair Imported",
      severity="medium", mitre=["t1098.004"], product="aws", service="ec2",
      when={"event_name": "ImportKeyPair"},
      fp=["Bootstrap of golden image", FP_AUTOMATION], playbook="tpl-persistence"),
    S(slug="aws-ec2-disable-api-stop-revoked", name="AWS EC2 DisableApiStop Protection Revoked",
      severity="medium", mitre=["t1485"], product="aws", service="ec2",
      when={"event_name": "ModifyInstanceAttribute", "attribute": "disableApiStop", "value": False},
      fp=["Decommissioning workflow"], playbook="tpl-impact"),
    S(slug="aws-ec2-userdata-modified-running", name="AWS EC2 UserData Modified On Running Instance",
      severity="high", mitre=["t1059.001", "t1059.004"], product="aws", service="ec2",
      when={"event_name": "ModifyInstanceAttribute", "attribute": "userData", "instance_state": "running"},
      fp=["Approved cloud-init re-run"], playbook="tpl-execution"),
    S(slug="aws-vpc-route-to-internet-gateway", name="AWS VPC Default Route Pointed At New IGW",
      severity="high", mitre=["t1090"], product="aws", service="ec2",
      when={"event_name": "CreateRoute", "destination_cidr": "0.0.0.0/0", "target_type": "internet-gateway"},
      fp=["New public subnet provisioning"], playbook="tpl-command-and-control"),
    S(slug="aws-security-group-rule-add-22-from-anywhere", name="AWS SG Rule Allows SSH From 0.0.0.0/0",
      severity="high", mitre=["t1133"], product="aws", service="ec2",
      when={"event_name": "AuthorizeSecurityGroupIngress", "ip_protocol": "tcp", "from_port": 22, "to_port": 22, "cidr": "0.0.0.0/0"},
      fp=["Bastion/jump-host with MFA"], playbook="tpl-initial-access"),
    S(slug="aws-security-group-rule-add-3389-from-anywhere", name="AWS SG Rule Allows RDP From 0.0.0.0/0",
      severity="high", mitre=["t1133"], product="aws", service="ec2",
      when={"event_name": "AuthorizeSecurityGroupIngress", "ip_protocol": "tcp", "from_port": 3389, "to_port": 3389, "cidr": "0.0.0.0/0"},
      fp=["Lab account by design"], playbook="tpl-initial-access"),
    S(slug="aws-vpc-peering-cross-org", name="AWS VPC Peering Connection Across Organizations",
      severity="high", mitre=["t1199"], product="aws", service="ec2",
      when={"event_name": "CreateVpcPeeringConnection", "peer_account_external": True},
      fp=["Approved partner network"], playbook="tpl-initial-access"),
    # ---- RDS (5) ----
    S(slug="aws-rds-publicly-accessible-true", name="AWS RDS Instance Modified To Publicly Accessible",
      severity="critical", mitre=["t1530"], product="aws", service="rds",
      when={"event_name_in": ["CreateDBInstance", "ModifyDBInstance"], "publicly_accessible": True},
      fp=["Lab/demo workload only"], playbook="tpl-data-exposure"),
    S(slug="aws-rds-snapshot-shared", name="AWS RDS Snapshot Shared With Other Account",
      severity="high", mitre=["t1537"], product="aws", service="rds",
      when={"event_name": "ModifyDBSnapshotAttribute", "shared_account_external": True},
      fp=["DR copy to disaster account"], playbook="tpl-exfiltration"),
    S(slug="aws-rds-iam-auth-disabled", name="AWS RDS IAM Authentication Disabled",
      severity="medium", mitre=["t1556"], product="aws", service="rds",
      when={"event_name": "ModifyDBInstance", "iam_database_authentication_enabled": False},
      fp=[FP_TUNING], playbook="tpl-defense-evasion"),
    S(slug="aws-rds-master-password-reset", name="AWS RDS Master User Password Reset",
      severity="high", mitre=["t1098"], product="aws", service="rds",
      when={"event_name": "ModifyDBInstance", "master_user_password_changed": True},
      fp=["Scheduled rotation"], playbook="tpl-credential-access"),
    S(slug="aws-rds-deletion-protection-disabled", name="AWS RDS Deletion Protection Disabled",
      severity="medium", mitre=["t1485"], product="aws", service="rds",
      when={"event_name": "ModifyDBInstance", "deletion_protection": False},
      fp=["Planned decommission"], playbook="tpl-impact"),
    # ---- Lambda (4) ----
    S(slug="aws-lambda-add-permission-anonymous", name="AWS Lambda AddPermission Allows Principal '*'",
      severity="critical", mitre=["t1190"], product="aws", service="lambda",
      when={"event_name": "AddPermission", "principal": "*"},
      fp=["Public webhook endpoint by design"], playbook="tpl-initial-access"),
    S(slug="aws-lambda-env-var-secret-pattern", name="AWS Lambda Env Var Contains Secret Pattern",
      severity="high", mitre=["t1552.001"], product="aws", service="lambda",
      when={"event_name_in": ["CreateFunction", "UpdateFunctionConfiguration"], "env_secret_pattern": True},
      fp=["Local-only fixture / unit-test value"], playbook="tpl-credential-access"),
    S(slug="aws-lambda-create-url-public", name="AWS Lambda Function URL With AuthType=NONE",
      severity="high", mitre=["t1190"], product="aws", service="lambda",
      when={"event_name": "CreateFunctionUrlConfig", "auth_type": "NONE"},
      fp=["Public ingest endpoint by design"], playbook="tpl-initial-access"),
    S(slug="aws-lambda-runtime-deprecated", name="AWS Lambda Function Uses Deprecated Runtime",
      severity="medium", mitre=["t1610"], product="aws", service="lambda",
      when={"event_name": "CreateFunction", "runtime_in": ["nodejs10.x", "nodejs12.x", "python2.7", "python3.6"]},
      fp=[FP_TUNING], playbook="tpl-vulnerability"),
    # ---- EKS / ECS (6) ----
    S(slug="aws-eks-cluster-public-endpoint", name="AWS EKS Cluster API Endpoint Made Public",
      severity="critical", mitre=["t1133"], product="aws", service="eks",
      when={"event_name_in": ["CreateCluster", "UpdateClusterConfig"], "endpoint_public_access": True, "public_access_cidrs_contains": "0.0.0.0/0"},
      fp=["Lab cluster"], playbook="tpl-initial-access"),
    S(slug="aws-eks-fargate-profile-default-ns", name="AWS EKS Fargate Profile Targets default Namespace",
      severity="medium", mitre=["t1610"], product="aws", service="eks",
      when={"event_name": "CreateFargateProfile", "namespace": "default"},
      fp=["Greenfield cluster"], playbook="tpl-execution"),
    S(slug="aws-ecs-task-privileged", name="AWS ECS Task Definition With privileged=true",
      severity="high", mitre=["t1611"], product="aws", service="ecs",
      when={"event_name": "RegisterTaskDefinition", "privileged": True},
      fp=["Sysdig / debugger task"], playbook="tpl-privilege-escalation"),
    S(slug="aws-ecs-execute-command-enabled", name="AWS ECS ExecuteCommand Enabled On Service",
      severity="medium", mitre=["t1059"], product="aws", service="ecs",
      when={"event_name_in": ["CreateService", "UpdateService"], "enable_execute_command": True},
      fp=["Debugging window"], playbook="tpl-execution"),
    S(slug="aws-ecr-repo-publicly-readable", name="AWS ECR Repository Policy Public",
      severity="high", mitre=["t1525"], product="aws", service="ecr",
      when={"event_name": "SetRepositoryPolicy", "policy_principal": "*"},
      fp=["Public images repo"], playbook="tpl-supply-chain"),
    S(slug="aws-ecr-image-scan-disabled", name="AWS ECR Image Scan-On-Push Disabled",
      severity="low", mitre=["t1610"], product="aws", service="ecr",
      when={"event_name": "PutImageScanningConfiguration", "scan_on_push": False},
      fp=[FP_TUNING], playbook="tpl-vulnerability"),
    # ---- KMS / Secrets (4) ----
    S(slug="aws-kms-key-policy-anonymous", name="AWS KMS Key Policy Allows Principal '*'",
      severity="critical", mitre=["t1552.001"], product="aws", service="kms",
      when={"event_name": "PutKeyPolicy", "policy_principal": "*"},
      fp=[], playbook="tpl-credential-access"),
    S(slug="aws-kms-schedule-key-deletion", name="AWS KMS ScheduleKeyDeletion Used",
      severity="high", mitre=["t1485"], product="aws", service="kms",
      when={"event_name": "ScheduleKeyDeletion"},
      fp=["Decommissioning"], playbook="tpl-impact"),
    S(slug="aws-secretsmanager-mass-getsecret", name="AWS SecretsManager Mass GetSecretValue",
      severity="high", mitre=["t1552.001"], product="aws", service="secretsmanager",
      when={"event_name": "GetSecretValue", "distinct_secrets_per_minute_gt": 30},
      fp=["Bootstrap of new microservice"], playbook="tpl-credential-access"),
    S(slug="aws-ssm-parameter-secure-no-kms", name="AWS SSM SecureString Parameter Created Without KMS",
      severity="medium", mitre=["t1552.001"], product="aws", service="ssm",
      when={"event_name": "PutParameter", "type": "SecureString", "key_id": None},
      fp=[FP_TUNING], playbook="tpl-credential-access"),
    # ---- CloudTrail / Config / GuardDuty / Org (5) ----
    S(slug="aws-config-recorder-stopped", name="AWS Config Recorder Stopped",
      severity="critical", mitre=["t1562.008"], product="aws", service="config",
      when={"event_name": "StopConfigurationRecorder"},
      fp=["Account decommission"], playbook="tpl-defense-evasion"),
    S(slug="aws-guardduty-detector-deleted", name="AWS GuardDuty Detector Deleted",
      severity="critical", mitre=["t1562.001"], product="aws", service="guardduty",
      when={"event_name": "DeleteDetector"},
      fp=["Region pruning approved"], playbook="tpl-defense-evasion"),
    S(slug="aws-securityhub-disabled", name="AWS SecurityHub DisableSecurityHub",
      severity="critical", mitre=["t1562.001"], product="aws", service="securityhub",
      when={"event_name": "DisableSecurityHub"},
      fp=["Account decommission"], playbook="tpl-defense-evasion"),
    S(slug="aws-cloudtrail-event-selector-narrowed", name="AWS CloudTrail Event Selector Narrowed",
      severity="high", mitre=["t1562.008"], product="aws", service="cloudtrail",
      when={"event_name": "PutEventSelectors", "selector_includes_management_events": False},
      fp=["Cost-optimisation work"], playbook="tpl-defense-evasion"),
    S(slug="aws-organizations-account-removed", name="AWS Organizations Account Removed",
      severity="high", mitre=["t1078.004"], product="aws", service="organizations",
      when={"event_name_in": ["RemoveAccountFromOrganization", "LeaveOrganization"]},
      fp=["Approved account divestiture"], playbook="tpl-defense-evasion"),
    # ---- Misc AWS (5) ----
    S(slug="aws-route53-domain-transfer-out", name="AWS Route53 Domain Transfer Out",
      severity="high", mitre=["t1583.001"], product="aws", service="route53domains",
      when={"event_name": "TransferDomainToAnotherAwsAccount"},
      fp=["Account merger workflow"], playbook="tpl-impact"),
    S(slug="aws-cloudfront-origin-changed", name="AWS CloudFront Origin Changed Mid-Service",
      severity="high", mitre=["t1565.002"], product="aws", service="cloudfront",
      when={"event_name": "UpdateDistribution", "origin_changed": True, "distribution_age_days_gt": 30},
      fp=["Approved migration"], playbook="tpl-impact"),
    S(slug="aws-waf-web-acl-disassociated", name="AWS WAF Web ACL Disassociated",
      severity="high", mitre=["t1562.001"], product="aws", service="wafv2",
      when={"event_name": "DisassociateWebACL"},
      fp=["Re-association in same window"], playbook="tpl-defense-evasion"),
    S(slug="aws-sns-topic-public-subscribe", name="AWS SNS Topic Policy Allows Anonymous Subscribe",
      severity="medium", mitre=["t1098"], product="aws", service="sns",
      when={"event_name": "SetTopicAttributes", "policy_principal": "*"},
      fp=["Public notifications topic"], playbook="tpl-data-exposure"),
    S(slug="aws-sqs-queue-public-policy", name="AWS SQS Queue Policy Allows Principal '*'",
      severity="medium", mitre=["t1098"], product="aws", service="sqs",
      when={"event_name": "SetQueueAttributes", "policy_principal": "*"},
      fp=["Public webhook ingestion"], playbook="tpl-initial-access"),
]


# ---------------------------------------------------------------------------
# Azure / M365 (35 rules)
# ---------------------------------------------------------------------------
AZURE_RULES: list[dict] = [
    # ---- Entra / AAD (12) ----
    S(slug="azure-ad-app-consent-grant", name="Entra ID Admin Consent Granted To App",
      severity="high", mitre=["t1528"], product="azure", service="entra-audit",
      when={"operation_name": "Consent to application", "consent_type": "AllPrincipals"},
      fp=["Sanctioned SaaS rollout"], playbook="tpl-credential-access"),
    S(slug="azure-ad-app-credential-added-out-of-hours", name="Entra ID App Credential Added Outside Business Hours",
      severity="high", mitre=["t1098.001"], product="azure", service="entra-audit",
      when={"operation_name": "Add service principal credentials", "is_business_hours": False},
      fp=["On-call engineer rotation"], playbook="tpl-persistence"),
    S(slug="azure-ad-conditional-access-bypass-rule", name="Entra ID Conditional Access Rule Excludes Privileged User",
      severity="high", mitre=["t1556"], product="azure", service="entra-audit",
      when={"operation_name": "Update policy", "policy_excludes_priv_user": True},
      fp=[FP_BREAK_GLASS], playbook="tpl-defense-evasion"),
    S(slug="azure-ad-mfa-method-removed-priv", name="Entra ID MFA Method Removed From Privileged User",
      severity="critical", mitre=["t1556.006"], product="azure", service="entra-audit",
      when={"operation_name_in": ["User registered security info", "User deleted security info"], "target_user_priv": True, "method_removed": True},
      fp=[FP_BREAK_GLASS], playbook="tpl-defense-evasion"),
    S(slug="azure-ad-pim-role-eligibility-self-assigned", name="Entra ID PIM Role Eligibility Self-Assigned",
      severity="high", mitre=["t1078.004"], product="azure", service="entra-audit",
      when={"operation_name": "Add eligible member to role", "actor_eq_target": True},
      fp=["Bootstrap by Global Admin"], playbook="tpl-privilege-escalation"),
    S(slug="azure-ad-app-permissions-graph-read-write-all", name="Entra ID App Granted Directory.ReadWrite.All",
      severity="critical", mitre=["t1098.003"], product="azure", service="entra-audit",
      when={"operation_name": "Update application", "permissions_added_contains_any": ["Directory.ReadWrite.All", "RoleManagement.ReadWrite.Directory"]},
      fp=["Approved IAM tooling"], playbook="tpl-privilege-escalation"),
    S(slug="azure-ad-bulk-user-creation", name="Entra ID Bulk User Creation Burst",
      severity="medium", mitre=["t1136.003"], product="azure", service="entra-audit",
      when={"operation_name": "Add user", "events_per_minute_gt": 25},
      fp=["Bulk onboarding"], playbook="tpl-persistence"),
    S(slug="azure-ad-named-location-removed", name="Entra ID Trusted Named Location Removed",
      severity="medium", mitre=["t1556"], product="azure", service="entra-audit",
      when={"operation_name": "Delete named location"},
      fp=["Office relocation project"], playbook="tpl-defense-evasion"),
    S(slug="azure-ad-legacy-auth-allowed", name="Entra ID Legacy Authentication Re-Enabled",
      severity="high", mitre=["t1556"], product="azure", service="entra-audit",
      when={"operation_name": "Update policy", "block_legacy_auth": False},
      fp=["Migration of legacy app"], playbook="tpl-defense-evasion"),
    S(slug="azure-ad-bulk-license-assignment", name="Entra ID Bulk License Assignment",
      severity="low", mitre=["t1078.004"], product="azure", service="entra-audit",
      when={"operation_name": "Change user license", "events_per_minute_gt": 50},
      fp=["Bulk onboarding"], playbook="tpl-discovery"),
    S(slug="azure-ad-admin-consent-workflow-disabled", name="Entra ID Admin Consent Workflow Disabled",
      severity="medium", mitre=["t1556"], product="azure", service="entra-audit",
      when={"operation_name": "Set Company Information", "admin_consent_workflow": False},
      fp=["Tenant config refactor"], playbook="tpl-defense-evasion"),
    S(slug="azure-ad-self-service-pwd-reset-policy-modified", name="Entra ID SSPR Policy Weakened",
      severity="medium", mitre=["t1556"], product="azure", service="entra-audit",
      when={"operation_name_in": ["Update password reset policy", "Disable password reset policy"]},
      fp=[FP_TUNING], playbook="tpl-defense-evasion"),
    # ---- ARM (8) ----
    S(slug="azure-arm-policy-assignment-deleted", name="Azure Policy Assignment Deleted",
      severity="high", mitre=["t1562.001"], product="azure", service="activity",
      when={"operation_name_endswith": "policyAssignments/delete", "scope_root": True},
      fp=["Policy refactor"], playbook="tpl-defense-evasion"),
    S(slug="azure-arm-blueprint-deleted", name="Azure Blueprint Assignment Removed",
      severity="medium", mitre=["t1562.001"], product="azure", service="activity",
      when={"operation_name_endswith": "blueprintAssignments/delete"},
      fp=["Subscription decommission"], playbook="tpl-defense-evasion"),
    S(slug="azure-arm-role-assignment-owner-tenant", name="Azure Role Assignment Owner At Tenant Scope",
      severity="critical", mitre=["t1078.004"], product="azure", service="activity",
      when={"operation_name_endswith": "roleAssignments/write", "role": "Owner", "scope_root": True},
      fp=[FP_BREAK_GLASS], playbook="tpl-privilege-escalation"),
    S(slug="azure-arm-locks-removed-bulk", name="Azure ResourceGroup Locks Removed In Bulk",
      severity="high", mitre=["t1485"], product="azure", service="activity",
      when={"operation_name_endswith": "locks/delete", "events_per_minute_gt": 10},
      fp=["Decommission project"], playbook="tpl-impact"),
    S(slug="azure-arm-diagnostic-settings-deleted", name="Azure Diagnostic Settings Deleted",
      severity="critical", mitre=["t1562.008"], product="azure", service="activity",
      when={"operation_name_endswith": "diagnosticSettings/delete"},
      fp=["Log pipeline migration"], playbook="tpl-defense-evasion"),
    S(slug="azure-arm-mass-resource-modify", name="Azure Mass Resource Modify Burst",
      severity="medium", mitre=["t1485"], product="azure", service="activity",
      when={"operation_name_endswith_any": ["/write", "/delete"], "events_per_minute_gt": 200},
      fp=["IaC pipeline run"], playbook="tpl-impact"),
    S(slug="azure-arm-management-group-removed", name="Azure Management Group Removed",
      severity="high", mitre=["t1485"], product="azure", service="activity",
      when={"operation_name_endswith": "managementGroups/delete"},
      fp=["Org restructure"], playbook="tpl-impact"),
    S(slug="azure-arm-subscription-transferred", name="Azure Subscription Transferred",
      severity="critical", mitre=["t1078.004"], product="azure", service="activity",
      when={"operation_name_contains": "subscriptions/transfer"},
      fp=["Approved EA migration"], playbook="tpl-impact"),
    # ---- Storage (5) ----
    S(slug="azure-storage-blob-anonymous-read", name="Azure Storage Container Allows Anonymous Read",
      severity="critical", mitre=["t1530"], product="azure", service="activity",
      when={"operation_name_endswith": "blobServices/containers/write", "public_access_in": ["Container", "Blob"]},
      fp=["Static-site container by design"], playbook="tpl-data-exposure"),
    S(slug="azure-storage-account-firewall-disabled", name="Azure Storage Account Firewall Disabled",
      severity="high", mitre=["t1133"], product="azure", service="activity",
      when={"operation_name_endswith": "storageAccounts/write", "default_action": "Allow"},
      fp=["Public datalake by design"], playbook="tpl-initial-access"),
    S(slug="azure-storage-shared-key-issued", name="Azure Storage Shared Access Signature Generated With Long TTL",
      severity="medium", mitre=["t1078"], product="azure", service="activity",
      when={"operation_name_contains": "ListKeys", "ttl_days_gt": 365},
      fp=[FP_AUTOMATION], playbook="tpl-credential-access"),
    S(slug="azure-storage-immutability-removed", name="Azure Storage Immutability Policy Removed",
      severity="high", mitre=["t1485"], product="azure", service="activity",
      when={"operation_name_endswith": "immutabilityPolicies/delete"},
      fp=["Retention review"], playbook="tpl-impact"),
    S(slug="azure-storage-soft-delete-disabled", name="Azure Blob Soft Delete Disabled",
      severity="medium", mitre=["t1490"], product="azure", service="activity",
      when={"operation_name_endswith": "blobServices/write", "delete_retention_enabled": False},
      fp=[FP_TUNING], playbook="tpl-impact"),
    # ---- Key Vault (5) ----
    S(slug="azure-keyvault-purge-protection-disabled", name="Azure Key Vault Purge Protection Disabled",
      severity="high", mitre=["t1485"], product="azure", service="keyvault",
      when={"operation_name_endswith": "vaults/write", "enable_purge_protection": False},
      fp=[FP_TUNING], playbook="tpl-impact"),
    S(slug="azure-keyvault-secret-mass-get", name="Azure Key Vault Mass GetSecret",
      severity="high", mitre=["t1552.001"], product="azure", service="keyvault",
      when={"operation_name": "SecretGet", "distinct_secrets_per_minute_gt": 30},
      fp=["App boot"], playbook="tpl-credential-access"),
    S(slug="azure-keyvault-access-policy-broadened", name="Azure Key Vault Access Policy Adds Permission '*'",
      severity="critical", mitre=["t1098"], product="azure", service="keyvault",
      when={"operation_name_endswith": "vaults/accessPolicies/write", "permissions_contains": "all"},
      fp=[], playbook="tpl-privilege-escalation"),
    S(slug="azure-keyvault-firewall-allow-all", name="Azure Key Vault Network ACL Allows All",
      severity="high", mitre=["t1133"], product="azure", service="keyvault",
      when={"operation_name_endswith": "vaults/write", "default_action": "Allow"},
      fp=[FP_TUNING], playbook="tpl-initial-access"),
    S(slug="azure-keyvault-key-export-allowed", name="Azure Key Vault Key Export Attribute Set",
      severity="high", mitre=["t1552"], product="azure", service="keyvault",
      when={"operation_name_endswith": "keys/create", "exportable": True},
      fp=["Approved cross-region migration"], playbook="tpl-credential-access"),
    # ---- AKS / Compute (5) ----
    S(slug="azure-aks-cluster-public-fqdn", name="Azure AKS Cluster API With Public FQDN",
      severity="high", mitre=["t1133"], product="azure", service="activity",
      when={"operation_name_endswith": "managedClusters/write", "private_cluster": False, "authorized_ip_ranges_empty": True},
      fp=["Lab"], playbook="tpl-initial-access"),
    S(slug="azure-aks-rbac-disabled", name="Azure AKS Cluster RBAC Disabled",
      severity="high", mitre=["t1556"], product="azure", service="activity",
      when={"operation_name_endswith": "managedClusters/write", "enable_rbac": False},
      fp=["Lab"], playbook="tpl-defense-evasion"),
    S(slug="azure-vm-runcommand", name="Azure VM RunCommand Invoked",
      severity="high", mitre=["t1059"], product="azure", service="activity",
      when={"operation_name_endswith": "virtualMachines/runCommand/action"},
      fp=["Approved DevOps script"], playbook="tpl-execution"),
    S(slug="azure-vm-extension-customscript", name="Azure VM CustomScript Extension Installed",
      severity="medium", mitre=["t1059"], product="azure", service="activity",
      when={"operation_name_endswith": "extensions/write", "extension_type": "CustomScript"},
      fp=["Cloud-init bootstrap"], playbook="tpl-execution"),
    S(slug="azure-vm-disk-encryption-disabled", name="Azure VM Disk Encryption Disabled",
      severity="medium", mitre=["t1485"], product="azure", service="activity",
      when={"operation_name_endswith": "encryptionExtensions/write", "encryption_enabled": False},
      fp=["Data classification change"], playbook="tpl-impact"),
]


# ---------------------------------------------------------------------------
# GCP (30 rules)
# ---------------------------------------------------------------------------
GCP_RULES: list[dict] = [
    # ---- IAM (10) ----
    S(slug="gcp-iam-allusers-binding", name="GCP IAM Binding Adds allUsers / allAuthenticatedUsers",
      severity="critical", mitre=["t1530"], product="gcp", service="audit",
      when={"method_name_endswith": "SetIamPolicy", "added_member_in": ["allUsers", "allAuthenticatedUsers"]},
      fp=["Public dataset by design"], playbook="tpl-data-exposure"),
    S(slug="gcp-iam-service-account-disable", name="GCP Service Account Disabled",
      severity="medium", mitre=["t1531"], product="gcp", service="audit",
      when={"method_name_endswith": "DisableServiceAccount"},
      fp=["Decommissioning"], playbook="tpl-impact"),
    S(slug="gcp-iam-service-account-actas-grant", name="GCP iam.serviceAccountUser Grant",
      severity="high", mitre=["t1078.004"], product="gcp", service="audit",
      when={"method_name_endswith": "SetIamPolicy", "role_added": "roles/iam.serviceAccountUser"},
      fp=[FP_AUTOMATION], playbook="tpl-privilege-escalation"),
    S(slug="gcp-iam-token-creator-grant", name="GCP iam.serviceAccountTokenCreator Grant",
      severity="high", mitre=["t1078.004"], product="gcp", service="audit",
      when={"method_name_endswith": "SetIamPolicy", "role_added": "roles/iam.serviceAccountTokenCreator"},
      fp=[FP_AUTOMATION], playbook="tpl-privilege-escalation"),
    S(slug="gcp-iam-billing-admin-grant", name="GCP roles/billing.admin Granted",
      severity="high", mitre=["t1098"], product="gcp", service="audit",
      when={"method_name_endswith": "SetIamPolicy", "role_added": "roles/billing.admin"},
      fp=["Org bootstrap"], playbook="tpl-privilege-escalation"),
    S(slug="gcp-iam-org-policy-disabled", name="GCP Organization Policy Constraint Disabled",
      severity="high", mitre=["t1562.001"], product="gcp", service="audit",
      when={"method_name_endswith": "SetOrgPolicy", "list_policy_all_values": "ALLOW"},
      fp=[FP_TUNING], playbook="tpl-defense-evasion"),
    S(slug="gcp-iam-service-account-key-mass-create", name="GCP Service Account Key Burst",
      severity="high", mitre=["t1098.001"], product="gcp", service="audit",
      when={"method_name_endswith": "CreateServiceAccountKey", "events_per_minute_gt": 5},
      fp=[FP_AUTOMATION], playbook="tpl-persistence"),
    S(slug="gcp-iam-grant-from-foreign-domain", name="GCP IAM Binding To External Domain",
      severity="high", mitre=["t1199"], product="gcp", service="audit",
      when={"method_name_endswith": "SetIamPolicy", "added_member_external_domain": True},
      fp=["Approved partner identity"], playbook="tpl-initial-access"),
    S(slug="gcp-iam-impersonation-burst", name="GCP Service Account Impersonation Burst",
      severity="high", mitre=["t1078.004"], product="gcp", service="audit",
      when={"method_name_endswith": "GenerateAccessToken", "distinct_targets_per_minute_gt": 10},
      fp=[FP_AUTOMATION], playbook="tpl-credential-access"),
    S(slug="gcp-iam-conditional-binding-removed", name="GCP IAM Conditional Binding Removed",
      severity="medium", mitre=["t1556"], product="gcp", service="audit",
      when={"method_name_endswith": "SetIamPolicy", "condition_removed": True},
      fp=[FP_TUNING], playbook="tpl-defense-evasion"),
    # ---- GCS (6) ----
    S(slug="gcp-gcs-bucket-iam-allusers", name="GCS Bucket IAM Granted To allUsers",
      severity="critical", mitre=["t1530"], product="gcp", service="audit",
      when={"method_name_endswith_any": ["storage.setIamPermissions", "storage.buckets.update"], "added_member_in": ["allUsers", "allAuthenticatedUsers"]},
      fp=["Public CDN bucket by design"], playbook="tpl-data-exposure"),
    S(slug="gcp-gcs-uniform-access-disabled", name="GCS Uniform Bucket-Level Access Disabled",
      severity="medium", mitre=["t1530"], product="gcp", service="audit",
      when={"method_name_endswith": "storage.buckets.update", "uniform_bucket_level_access": False},
      fp=[FP_TUNING], playbook="tpl-data-exposure"),
    S(slug="gcp-gcs-mass-delete", name="GCS Mass Object Delete Burst",
      severity="critical", mitre=["t1485"], product="gcp", service="audit",
      when={"method_name": "storage.objects.delete", "events_per_minute_gt": 1000},
      fp=["Lifecycle rule"], playbook="tpl-impact"),
    S(slug="gcp-gcs-bucket-retention-removed", name="GCS Bucket Retention Policy Removed",
      severity="high", mitre=["t1485"], product="gcp", service="audit",
      when={"method_name_endswith": "storage.buckets.removeRetentionPolicy"},
      fp=[FP_TUNING], playbook="tpl-impact"),
    S(slug="gcp-gcs-versioning-disabled", name="GCS Object Versioning Disabled",
      severity="medium", mitre=["t1490"], product="gcp", service="audit",
      when={"method_name_endswith": "storage.buckets.update", "versioning_enabled": False},
      fp=[FP_TUNING], playbook="tpl-impact"),
    S(slug="gcp-gcs-cors-wildcard", name="GCS Bucket CORS Wildcard Origin",
      severity="medium", mitre=["t1530"], product="gcp", service="audit",
      when={"method_name_endswith": "storage.buckets.update", "cors_origin": "*"},
      fp=["Public API by design"], playbook="tpl-data-exposure"),
    # ---- GKE (5) ----
    S(slug="gcp-gke-rbac-anonymous", name="GKE Cluster Anonymous Auth Enabled",
      severity="critical", mitre=["t1133"], product="gcp", service="audit",
      when={"method_name_endswith": "clusters.update", "anonymous_auth": True},
      fp=[], playbook="tpl-initial-access"),
    S(slug="gcp-gke-private-cluster-disabled", name="GKE Cluster Private Cluster Disabled",
      severity="high", mitre=["t1133"], product="gcp", service="audit",
      when={"method_name_endswith": "clusters.update", "private_cluster": False, "authorized_networks_empty": True},
      fp=["Lab cluster"], playbook="tpl-initial-access"),
    S(slug="gcp-gke-workload-identity-disabled", name="GKE Workload Identity Disabled",
      severity="medium", mitre=["t1078"], product="gcp", service="audit",
      when={"method_name_endswith": "clusters.update", "workload_identity_config": None},
      fp=[FP_TUNING], playbook="tpl-defense-evasion"),
    S(slug="gcp-gke-shielded-nodes-disabled", name="GKE Shielded Nodes Disabled",
      severity="medium", mitre=["t1610"], product="gcp", service="audit",
      when={"method_name_endswith": "clusters.update", "shielded_nodes": False},
      fp=[FP_TUNING], playbook="tpl-defense-evasion"),
    S(slug="gcp-gke-binary-auth-disabled", name="GKE Binary Authorization Disabled",
      severity="medium", mitre=["t1610"], product="gcp", service="audit",
      when={"method_name_endswith": "clusters.update", "binary_authorization": False},
      fp=[FP_TUNING], playbook="tpl-supply-chain"),
    # ---- BigQuery (5) ----
    S(slug="gcp-bq-dataset-allusers-access", name="BigQuery Dataset ACL Adds allUsers",
      severity="critical", mitre=["t1530"], product="gcp", service="audit",
      when={"method_name": "datasetservice.update", "added_member_in": ["allUsers", "allAuthenticatedUsers"]},
      fp=["Public dataset by design"], playbook="tpl-data-exposure"),
    S(slug="gcp-bq-mass-export", name="BigQuery Mass Export Burst",
      severity="high", mitre=["t1567.002"], product="gcp", service="audit",
      when={"method_name_in": ["jobservice.jobcompleted", "jobs.insert"], "job_type": "EXPORT", "events_per_minute_gt": 5},
      fp=["Scheduled BI export"], playbook="tpl-exfiltration"),
    S(slug="gcp-bq-cross-project-query", name="BigQuery Query Across External Project",
      severity="medium", mitre=["t1083"], product="gcp", service="audit",
      when={"method_name": "jobservice.jobcompleted", "referenced_project_external": True},
      fp=["Cross-project analytics by design"], playbook="tpl-discovery"),
    S(slug="gcp-bq-table-deleted-recently-created", name="BigQuery Table Deleted Within 1 Hour Of Creation",
      severity="medium", mitre=["t1485"], product="gcp", service="audit",
      when={"method_name": "tableservice.delete", "table_age_minutes_lt": 60},
      fp=["Test/CI run"], playbook="tpl-impact"),
    S(slug="gcp-bq-cmek-removed", name="BigQuery Dataset CMEK Removed",
      severity="medium", mitre=["t1485"], product="gcp", service="audit",
      when={"method_name": "datasetservice.update", "kms_key_removed": True},
      fp=[FP_TUNING], playbook="tpl-impact"),
    # ---- Compute / Networking (4) ----
    S(slug="gcp-compute-firewall-source-any-port-any", name="GCP Firewall Rule 0.0.0.0/0 With Any Port",
      severity="high", mitre=["t1133"], product="gcp", service="audit",
      when={"method_name_endswith": "firewalls.insert", "source_ranges_contains": "0.0.0.0/0", "port_any": True},
      fp=["Lab project"], playbook="tpl-initial-access"),
    S(slug="gcp-compute-instance-public-ip-attached", name="GCP Compute Public IP Attached To Instance",
      severity="medium", mitre=["t1133"], product="gcp", service="audit",
      when={"method_name_endswith": "instances.insert", "external_ip_attached": True, "label_internal": True},
      fp=[FP_TUNING], playbook="tpl-initial-access"),
    S(slug="gcp-compute-os-login-disabled", name="GCP Project OS Login Disabled",
      severity="medium", mitre=["t1556"], product="gcp", service="audit",
      when={"method_name_endswith": "projects.setCommonInstanceMetadata", "metadata_oslogin": "FALSE"},
      fp=[FP_TUNING], playbook="tpl-defense-evasion"),
    S(slug="gcp-compute-shielded-vm-disabled", name="GCP Compute Shielded VM Disabled",
      severity="medium", mitre=["t1610"], product="gcp", service="audit",
      when={"method_name_endswith": "instances.update", "shielded_instance_config": False},
      fp=[FP_TUNING], playbook="tpl-defense-evasion"),
]


# ---------------------------------------------------------------------------
# Kubernetes (15 rules) - cloud-agnostic
# ---------------------------------------------------------------------------
K8S_RULES: list[dict] = [
    S(slug="k8s-cluster-admin-binding-non-system", name="Kubernetes cluster-admin ClusterRoleBinding For Non-System Subject",
      severity="critical", mitre=["t1098.001"], product="kubernetes", service="audit",
      when={"verb": "create", "object_resource": "clusterrolebindings", "role_ref_name": "cluster-admin", "subject_namespace_not": "kube-system"},
      fp=["Bootstrap of new cluster"], playbook="tpl-privilege-escalation"),
    S(slug="k8s-secret-mass-get", name="Kubernetes Secret Mass Get",
      severity="high", mitre=["t1552.001"], product="kubernetes", service="audit",
      when={"verb": "get", "object_resource": "secrets", "distinct_secrets_per_minute_gt": 30},
      fp=["Operator boot"], playbook="tpl-credential-access"),
    S(slug="k8s-pod-exec-prod-namespace", name="Kubernetes pods/exec In Production Namespace",
      severity="high", mitre=["t1610"], product="kubernetes", service="audit",
      when={"verb": "create", "object_resource": "pods/exec", "object_namespace_in": ["prod", "production"]},
      fp=["DFIR responder", FP_FORENSIC], playbook="tpl-execution"),
    S(slug="k8s-pod-attach-prod-namespace", name="Kubernetes pods/attach In Production Namespace",
      severity="medium", mitre=["t1610"], product="kubernetes", service="audit",
      when={"verb": "create", "object_resource": "pods/attach", "object_namespace_in": ["prod", "production"]},
      fp=[FP_FORENSIC], playbook="tpl-execution"),
    S(slug="k8s-anonymous-system-unauth", name="Kubernetes Request By system:anonymous",
      severity="critical", mitre=["t1078"], product="kubernetes", service="audit",
      when={"user_name": "system:anonymous", "response_status_code_lt": 400},
      fp=["Healthz probe (must be ticketed)"], playbook="tpl-initial-access"),
    S(slug="k8s-rbac-wildcard-verb", name="Kubernetes Role Created With Wildcard Verb",
      severity="high", mitre=["t1078"], product="kubernetes", service="audit",
      when={"verb_in": ["create", "update"], "object_resource_in": ["roles", "clusterroles"], "rule_verbs_contains": "*"},
      fp=["Operator chart"], playbook="tpl-privilege-escalation"),
    S(slug="k8s-pod-host-pid-enabled", name="Kubernetes Pod hostPID=true",
      severity="high", mitre=["t1611"], product="kubernetes", service="audit",
      when={"verb": "create", "object_resource": "pods", "host_pid": True},
      fp=["DaemonSet for monitoring"], playbook="tpl-privilege-escalation"),
    S(slug="k8s-pod-host-network-enabled", name="Kubernetes Pod hostNetwork=true",
      severity="high", mitre=["t1611"], product="kubernetes", service="audit",
      when={"verb": "create", "object_resource": "pods", "host_network": True},
      fp=["CNI / kube-proxy DaemonSet"], playbook="tpl-privilege-escalation"),
    S(slug="k8s-pod-privileged-container", name="Kubernetes Privileged Container Created",
      severity="high", mitre=["t1611"], product="kubernetes", service="audit",
      when={"verb": "create", "object_resource": "pods", "privileged": True},
      fp=["Sysdig / Falco DaemonSet"], playbook="tpl-privilege-escalation"),
    S(slug="k8s-validating-webhook-deleted", name="Kubernetes ValidatingWebhookConfiguration Deleted",
      severity="medium", mitre=["t1562.001"], product="kubernetes", service="audit",
      when={"verb": "delete", "object_resource": "validatingwebhookconfigurations"},
      fp=[FP_TUNING], playbook="tpl-defense-evasion"),
    S(slug="k8s-mutating-webhook-suspicious-target", name="Kubernetes MutatingWebhookConfiguration With External Endpoint",
      severity="high", mitre=["t1556"], product="kubernetes", service="audit",
      when={"verb_in": ["create", "update"], "object_resource": "mutatingwebhookconfigurations", "webhook_url_external": True},
      fp=["Approved policy controller"], playbook="tpl-defense-evasion"),
    S(slug="k8s-service-account-token-mount-default", name="Kubernetes Pod Default ServiceAccount Token Mount",
      severity="low", mitre=["t1078"], product="kubernetes", service="audit",
      when={"verb": "create", "object_resource": "pods", "service_account": "default", "automount_token": True},
      fp=["Greenfield workload"], playbook="tpl-credential-access"),
    S(slug="k8s-impersonation-by-user", name="Kubernetes Impersonate Privileged User",
      severity="high", mitre=["t1078.001"], product="kubernetes", service="audit",
      when={"verb_contains": "impersonate", "impersonated_user_in": ["system:masters", "kubernetes-admin"]},
      fp=[FP_FORENSIC], playbook="tpl-privilege-escalation"),
    S(slug="k8s-namespace-deletion-prod", name="Kubernetes Production Namespace Deleted",
      severity="critical", mitre=["t1485"], product="kubernetes", service="audit",
      when={"verb": "delete", "object_resource": "namespaces", "object_name_in": ["prod", "production"]},
      fp=[FP_BREAK_GLASS], playbook="tpl-impact"),
    S(slug="k8s-network-policy-deleted-prod", name="Kubernetes NetworkPolicy Deleted In Production",
      severity="high", mitre=["t1562.004"], product="kubernetes", service="audit",
      when={"verb": "delete", "object_resource": "networkpolicies", "object_namespace_in": ["prod", "production"]},
      fp=[FP_TUNING], playbook="tpl-defense-evasion"),
]


# ---------------------------------------------------------------------------
# Multi-cloud / SaaS-cloud (10 rules)
# ---------------------------------------------------------------------------
MULTI_CLOUD_RULES: list[dict] = [
    S(slug="cloud-cloudflare-zone-transfer", name="Cloudflare Zone Transferred Out Of Account",
      severity="high", mitre=["t1583.001"], product="cloudflare", service="audit",
      when={"action": "zone.transfer_out"},
      fp=["Approved org migration"], playbook="tpl-impact"),
    S(slug="cloud-cloudflare-waf-rule-disabled", name="Cloudflare WAF Rule Disabled",
      severity="high", mitre=["t1562.001"], product="cloudflare", service="audit",
      when={"action_in": ["firewall_rule.disable", "waf_rule.disable"]},
      fp=[FP_TUNING], playbook="tpl-defense-evasion"),
    S(slug="cloud-cloudflare-access-policy-bypass", name="Cloudflare Access Policy Bypass Granted",
      severity="critical", mitre=["t1556"], product="cloudflare", service="audit",
      when={"action": "access_policy.create", "decision": "bypass"},
      fp=[FP_BREAK_GLASS], playbook="tpl-defense-evasion"),
    S(slug="cloud-do-droplet-snapshot-shared", name="DigitalOcean Droplet Snapshot Transferred",
      severity="high", mitre=["t1537"], product="digitalocean", service="api",
      when={"action": "snapshot.transfer", "destination_account_external": True},
      fp=["Approved DR copy"], playbook="tpl-exfiltration"),
    S(slug="cloud-oci-iam-tenant-admin-binding", name="OCI Tenant Administrators Group Membership Added",
      severity="critical", mitre=["t1078.004"], product="oci", service="audit",
      when={"event_name": "AddUserToGroup", "group": "Administrators", "compartment": "tenancy"},
      fp=[FP_BREAK_GLASS], playbook="tpl-privilege-escalation"),
    S(slug="cloud-multi-cross-cloud-mass-egress", name="Multi-Cloud Cross-Cloud Mass Egress Burst",
      severity="high", mitre=["t1567"], product="multi-cloud", service="netflow",
      when={"src_cloud_in": ["aws", "azure", "gcp"], "dst_cloud_in": ["aws", "azure", "gcp"], "src_cloud_neq_dst_cloud": True, "bytes_out_per_minute_gt": 1073741824},
      fp=["Approved cross-cloud replication pipeline"], playbook="tpl-exfiltration"),
    S(slug="cloud-iac-drift-bypassed", name="Infra-As-Code Drift Bypassed With Manual Override",
      severity="medium", mitre=["t1610"], product="multi-cloud", service="iac",
      when={"action": "manual_override", "approver_in": ["self"], "out_of_hours": True},
      fp=[FP_BREAK_GLASS], playbook="tpl-impact"),
    S(slug="cloud-terraform-state-modified-direct", name="Terraform State File Modified Outside Pipeline",
      severity="high", mitre=["t1565.001"], product="multi-cloud", service="iac",
      when={"action": "state.modify", "actor_in_pipeline": False},
      fp=["Manual recovery (incident-tracked)"], playbook="tpl-impact"),
    S(slug="cloud-saml-idp-trust-changed", name="Cloud Provider SAML IdP Trust Changed",
      severity="high", mitre=["t1556"], product="multi-cloud", service="iam",
      when={"event_name_in": ["UpdateSAMLProvider", "Update federation configuration", "SetIdentityProvider"], "metadata_url_changed": True},
      fp=["IdP migration (must be ticketed)"], playbook="tpl-defense-evasion"),
    S(slug="cloud-org-rootmail-modified", name="Cloud Provider Root/Owner Email Modified",
      severity="critical", mitre=["t1078.004"], product="multi-cloud", service="iam",
      when={"event_name_in": ["UpdateAccountEmail", "Update tenant primary contact", "ChangeRootMail"], "actor_eq_target": False},
      fp=["Approved ownership transfer"], playbook="tpl-account-manipulation"),
]


# ---------------------------------------------------------------------------
# Combined CLOUD extras
# ---------------------------------------------------------------------------
CLOUD_EXTRA: list[dict] = [
    *AWS_RULES,
    *AZURE_RULES,
    *GCP_RULES,
    *K8S_RULES,
    *MULTI_CLOUD_RULES,
]


if __name__ == "__main__":
    print(f"AWS:        {len(AWS_RULES)}")
    print(f"Azure:      {len(AZURE_RULES)}")
    print(f"GCP:        {len(GCP_RULES)}")
    print(f"Kubernetes: {len(K8S_RULES)}")
    print(f"Multi:      {len(MULTI_CLOUD_RULES)}")
    print(f"TOTAL:      {len(CLOUD_EXTRA)}")
