"""
AiSOC Detection Pack v1 - Rule Specifications
==============================================

Single source of truth for the 200-rule curated detection pack.

Schema for each rule entry:
    (slug, name, severity, mitre[], log_source, condition, false_positives[], playbook?, positive_fixture, negative_fixture)

Where:
    positive_fixture = dict that the rule's condition should match
    negative_fixture = dict structurally similar but specifically tuned to NOT match

The generator script (`scripts/generate_detections.py`) walks this table to
emit YAML rules + fixtures. Validator (`scripts/validate_detections.py`)
runs fixture-replay against this same table to ensure positive matches and
negative doesn't.

Distribution per plan:
    cloud:        40
    identity:     40
    endpoint:     40
    network:      30
    application:  30
    data-exfil:   20
    -------------------
    Total:       200
"""

from __future__ import annotations

# fmt: off

# =============================================================================
# CLOUD (40)
# =============================================================================
CLOUD: list[dict] = [
    # AWS (15)
    {
        "slug": "aws-root-account-login",
        "name": "AWS Root Account Console Login",
        "description": "Detects any console sign-in event using the AWS root account. Root account usage outside of initial setup or emergency break-glass scenarios should trigger immediate investigation. Best practice requires MFA on the root account.",
        "severity": "critical",
        "mitre": ["t1078.004"],
        "log_source": {"product": "aws", "service": "cloudtrail"},
        "fields": {"event_name", "user_type", "error_code"},
        "match_when": {"event_name": "ConsoleLogin", "user_type": "Root", "error_code": None},
        "fp": ["Break-glass emergency access (must be documented)", "Initial account setup (one-time)"],
        "playbook": "tpl-privilege-escalation",
        "positive": {"event_name": "ConsoleLogin", "user_type": "Root", "error_code": None, "src_ip": "203.0.113.7"},
        "negative": {"event_name": "ConsoleLogin", "user_type": "IAMUser", "error_code": None, "src_ip": "203.0.113.7"},
    },
    {
        "slug": "aws-iam-enumeration",
        "name": "AWS IAM Enumeration Burst",
        "severity": "high",
        "mitre": ["t1087.004", "t1069.003"],
        "log_source": {"product": "aws", "service": "cloudtrail"},
        "fields": {"event_source", "event_name_count", "time_window_minutes"},
        "match_when": {"event_source": "iam.amazonaws.com", "event_name_count_gt": 25, "time_window_minutes_lt": 5},
        "fp": ["Compliance scanners (AWS Config, Prowler, CloudCustodian)", "IaC tools running plan/apply"],
        "playbook": "tpl-cloud-recon",
        "positive": {"event_source": "iam.amazonaws.com", "event_name_count": 60, "time_window_minutes": 3, "user_arn": "arn:aws:iam::111:user/contractor"},
        "negative": {"event_source": "iam.amazonaws.com", "event_name_count": 4, "time_window_minutes": 5, "user_arn": "arn:aws:iam::111:user/admin"},
    },
    {
        "slug": "aws-s3-public-bucket",
        "name": "AWS S3 Bucket Made Public",
        "description": "Detects when an S3 bucket ACL or bucket policy is modified to allow public read or public read-write access, which can lead to data exposure or unauthorised data exfiltration.",
        "severity": "high",
        "mitre": ["t1530"],
        "log_source": {"product": "aws", "service": "cloudtrail"},
        "fields": {"event_name", "request_acl", "request_policy"},
        "match_when": {"event_name_in": ["PutBucketAcl", "PutBucketPolicy"], "public_grant": True},
        "fp": ["Static website hosting bucket (must be tagged purpose=public)", "Open data publication"],
        "playbook": "tpl-data-exposure",
        "positive": {"event_name": "PutBucketAcl", "public_grant": True, "bucket": "customer-pii"},
        "negative": {"event_name": "PutBucketAcl", "public_grant": False, "bucket": "customer-pii"},
    },
    {
        "slug": "aws-s3-bucket-deletion",
        "name": "AWS S3 Bucket Deletion",
        "severity": "high",
        "mitre": ["t1485"],
        "log_source": {"product": "aws", "service": "cloudtrail"},
        "fields": {"event_name"},
        "match_when": {"event_name": "DeleteBucket"},
        "fp": ["Automated cleanup of ephemeral testing buckets", "Decommission via change-control ticket"],
        "playbook": "tpl-data-destruction",
        "positive": {"event_name": "DeleteBucket", "bucket": "prod-backups", "user_arn": "arn:aws:iam::111:user/contractor"},
        "negative": {"event_name": "DeleteObject", "bucket": "prod-backups", "user_arn": "arn:aws:iam::111:user/admin"},
    },
    {
        "slug": "aws-ec2-launch-foreign-region",
        "name": "AWS EC2 Instance Launched in Unauthorized Region",
        "severity": "medium",
        "mitre": ["t1578.002"],
        "log_source": {"product": "aws", "service": "cloudtrail"},
        "fields": {"event_name", "aws_region"},
        "match_when": {"event_name": "RunInstances", "aws_region_not_in": ["us-east-1", "us-west-2", "eu-west-1"]},
        "fp": ["DR/failover testing (announced)", "Approved expansion to new region (change ticket)"],
        "playbook": "tpl-cloud-anomaly",
        "positive": {"event_name": "RunInstances", "aws_region": "ap-northeast-3"},
        "negative": {"event_name": "RunInstances", "aws_region": "us-east-1"},
    },
    {
        "slug": "aws-security-group-open-world",
        "name": "AWS Security Group Opened to 0.0.0.0/0",
        "severity": "high",
        "mitre": ["t1190", "t1133"],
        "log_source": {"product": "aws", "service": "cloudtrail"},
        "fields": {"event_name", "ip_range", "port"},
        "match_when": {"event_name": "AuthorizeSecurityGroupIngress", "ip_range": "0.0.0.0/0", "port_in": [22, 3389, 3306, 5432, 1433, 6379]},
        "fp": ["Public load balancers (must be tagged role=public-lb)", "WAF-protected origins"],
        "playbook": "tpl-cloud-misconfig",
        "positive": {"event_name": "AuthorizeSecurityGroupIngress", "ip_range": "0.0.0.0/0", "port": 22, "sg_id": "sg-prod-db"},
        "negative": {"event_name": "AuthorizeSecurityGroupIngress", "ip_range": "10.0.0.0/8", "port": 22, "sg_id": "sg-prod-db"},
    },
    {
        "slug": "aws-iam-policy-permissive",
        "name": "AWS IAM Policy with Wildcard Action",
        "severity": "high",
        "mitre": ["t1078.004", "t1098.001"],
        "log_source": {"product": "aws", "service": "cloudtrail"},
        "fields": {"event_name", "policy_action", "policy_resource"},
        "match_when": {"event_name_in": ["PutUserPolicy", "PutRolePolicy", "AttachUserPolicy"], "policy_action": "*", "policy_resource": "*"},
        "fp": ["Bootstrap admin role (one-time, change ticketed)", "Break-glass policy"],
        "playbook": "tpl-privilege-escalation",
        "positive": {"event_name": "PutRolePolicy", "policy_action": "*", "policy_resource": "*", "role": "deploy-bot"},
        "negative": {"event_name": "PutRolePolicy", "policy_action": "s3:GetObject", "policy_resource": "arn:aws:s3:::reports/*", "role": "deploy-bot"},
    },
    {
        "slug": "aws-kms-key-disable",
        "name": "AWS KMS Key Disabled or Scheduled for Deletion",
        "severity": "critical",
        "mitre": ["t1485", "t1486"],
        "log_source": {"product": "aws", "service": "cloudtrail"},
        "fields": {"event_name"},
        "match_when": {"event_name_in": ["DisableKey", "ScheduleKeyDeletion"]},
        "fp": ["Decommission of expired key material (must reference change ticket)"],
        "playbook": "tpl-data-destruction",
        "positive": {"event_name": "ScheduleKeyDeletion", "key_id": "alias/prod-encrypt", "user_arn": "arn:aws:iam::111:user/intern"},
        "negative": {"event_name": "EnableKey", "key_id": "alias/prod-encrypt", "user_arn": "arn:aws:iam::111:user/admin"},
    },
    {
        "slug": "aws-cloudtrail-disabled",
        "name": "AWS CloudTrail Logging Disabled",
        "severity": "critical",
        "mitre": ["t1562.008"],
        "log_source": {"product": "aws", "service": "cloudtrail"},
        "fields": {"event_name"},
        "match_when": {"event_name_in": ["StopLogging", "DeleteTrail", "UpdateTrail"]},
        "fp": ["Log-trail consolidation during account merge (change ticketed)"],
        "playbook": "tpl-defense-evasion",
        "positive": {"event_name": "StopLogging", "trail_name": "org-default", "user_arn": "arn:aws:iam::111:user/contractor"},
        "negative": {"event_name": "StartLogging", "trail_name": "org-default", "user_arn": "arn:aws:iam::111:user/admin"},
    },
    {
        "slug": "aws-lambda-permissive-trigger",
        "name": "AWS Lambda Function with Public Invoke Permission",
        "severity": "medium",
        "mitre": ["t1190"],
        "log_source": {"product": "aws", "service": "cloudtrail"},
        "fields": {"event_name", "principal"},
        "match_when": {"event_name": "AddPermission", "principal": "*"},
        "fp": ["Public webhook endpoint (must have purpose=public-webhook tag)"],
        "playbook": "tpl-cloud-misconfig",
        "positive": {"event_name": "AddPermission", "principal": "*", "function": "process-customer-pii"},
        "negative": {"event_name": "AddPermission", "principal": "arn:aws:iam::222:role/partner", "function": "process-customer-pii"},
    },
    {
        "slug": "aws-vpc-flow-logs-disabled",
        "name": "AWS VPC Flow Logs Disabled",
        "severity": "high",
        "mitre": ["t1562.008"],
        "log_source": {"product": "aws", "service": "cloudtrail"},
        "fields": {"event_name"},
        "match_when": {"event_name": "DeleteFlowLogs"},
        "fp": ["VPC decommission (change ticketed, vpc-state=deleting tag)"],
        "playbook": "tpl-defense-evasion",
        "positive": {"event_name": "DeleteFlowLogs", "vpc_id": "vpc-prod"},
        "negative": {"event_name": "CreateFlowLogs", "vpc_id": "vpc-prod"},
    },
    {
        "slug": "aws-rds-publicly-accessible",
        "name": "AWS RDS Instance Set Publicly Accessible",
        "severity": "high",
        "mitre": ["t1190", "t1530"],
        "log_source": {"product": "aws", "service": "cloudtrail"},
        "fields": {"event_name", "publicly_accessible"},
        "match_when": {"event_name_in": ["CreateDBInstance", "ModifyDBInstance"], "publicly_accessible": True},
        "fp": ["Test/sandbox RDS bound to bastion subnet only (must not happen)"],
        "playbook": "tpl-data-exposure",
        "positive": {"event_name": "ModifyDBInstance", "publicly_accessible": True, "db_id": "prod-pii"},
        "negative": {"event_name": "ModifyDBInstance", "publicly_accessible": False, "db_id": "prod-pii"},
    },
    {
        "slug": "aws-ebs-snapshot-public",
        "name": "AWS EBS Snapshot Made Public",
        "severity": "critical",
        "mitre": ["t1530"],
        "log_source": {"product": "aws", "service": "cloudtrail"},
        "fields": {"event_name", "createvolumepermission"},
        "match_when": {"event_name": "ModifySnapshotAttribute", "createvolumepermission": "all"},
        "fp": ["Public AMI publication for community open-source projects (must be tagged purpose=public-ami)"],
        "playbook": "tpl-data-exposure",
        "positive": {"event_name": "ModifySnapshotAttribute", "createvolumepermission": "all", "snapshot_id": "snap-prod-pii"},
        "negative": {"event_name": "ModifySnapshotAttribute", "createvolumepermission": "self", "snapshot_id": "snap-prod-pii"},
    },
    {
        "slug": "aws-cross-account-assumerole",
        "name": "AWS AssumeRole from Untrusted External Account",
        "severity": "high",
        "mitre": ["t1078.004", "t1199"],
        "log_source": {"product": "aws", "service": "cloudtrail"},
        "fields": {"event_name", "user_arn"},
        "match_when": {"event_name": "AssumeRole", "user_arn_external_account": True, "external_account_in_allowlist": False},
        "fp": ["Trusted partner accounts (must be in allowlist)", "Org-internal cross-account scripts"],
        "playbook": "tpl-cloud-anomaly",
        "positive": {"event_name": "AssumeRole", "user_arn": "arn:aws:sts::999999999999:assumed-role/external", "user_arn_external_account": True, "external_account_in_allowlist": False},
        "negative": {"event_name": "AssumeRole", "user_arn": "arn:aws:sts::111111111111:assumed-role/internal", "user_arn_external_account": False},
    },
    {
        "slug": "aws-s3-mass-getobject",
        "name": "AWS S3 GetObject Volume Anomaly per Principal",
        "severity": "high",
        "mitre": ["t1530"],
        "log_source": {"product": "aws", "service": "cloudtrail"},
        "fields": {"event_name", "object_count_per_principal", "time_window_minutes"},
        "match_when": {"event_name": "GetObject", "object_count_per_principal_gt": 5000, "time_window_minutes_lt": 30},
        "fp": ["Bulk-export jobs (must use tagged batch role)", "Backup tooling"],
        "playbook": "tpl-data-exfil",
        "positive": {"event_name": "GetObject", "object_count_per_principal": 12000, "time_window_minutes": 12, "user_arn": "arn:aws:iam::111:user/intern"},
        "negative": {"event_name": "GetObject", "object_count_per_principal": 35, "time_window_minutes": 30, "user_arn": "arn:aws:iam::111:user/intern"},
    },
    # Azure (10)
    {
        "slug": "azure-ad-role-owner-assignment",
        "name": "Azure AD Owner/Global-Admin Role Assignment",
        "severity": "critical",
        "mitre": ["t1098.003"],
        "log_source": {"product": "azure", "service": "azuread-audit"},
        "fields": {"operation_name", "role_name"},
        "match_when": {"operation_name": "AddMemberToRole", "role_name_in": ["Global Administrator", "Privileged Role Administrator", "Owner"]},
        "fp": ["Initial tenant bootstrap (must be ticketed)", "Break-glass account assignment"],
        "playbook": "tpl-privilege-escalation",
        "positive": {"operation_name": "AddMemberToRole", "role_name": "Global Administrator", "target_user": "user@corp.com"},
        "negative": {"operation_name": "AddMemberToRole", "role_name": "Reader", "target_user": "user@corp.com"},
    },
    {
        "slug": "azure-ad-app-secret-added",
        "name": "Azure AD Application Credential Added",
        "severity": "high",
        "mitre": ["t1098.001"],
        "log_source": {"product": "azure", "service": "azuread-audit"},
        "fields": {"operation_name"},
        "match_when": {"operation_name": "Update application - Certificates and secrets management"},
        "fp": ["Application owner rotating credentials (must be tagged change ticketed)"],
        "playbook": "tpl-privilege-escalation",
        "positive": {"operation_name": "Update application - Certificates and secrets management", "app_id": "graph-reader-app"},
        "negative": {"operation_name": "Update application - Properties", "app_id": "graph-reader-app"},
    },
    {
        "slug": "azure-conditional-access-disabled",
        "name": "Azure AD Conditional Access Policy Disabled or Removed",
        "severity": "critical",
        "mitre": ["t1562.001"],
        "log_source": {"product": "azure", "service": "azuread-audit"},
        "fields": {"operation_name", "policy_state"},
        "match_when": {"operation_name_in": ["Update conditional access policy", "Delete conditional access policy"], "policy_state": "disabled"},
        "fp": ["Policy migration (must reference replacement policy)"],
        "playbook": "tpl-defense-evasion",
        "positive": {"operation_name": "Update conditional access policy", "policy_state": "disabled", "policy_name": "MFA-required"},
        "negative": {"operation_name": "Update conditional access policy", "policy_state": "enabled", "policy_name": "MFA-required"},
    },
    {
        "slug": "azure-keyvault-key-deleted",
        "name": "Azure Key Vault Key Deleted",
        "severity": "high",
        "mitre": ["t1485"],
        "log_source": {"product": "azure", "service": "keyvault"},
        "fields": {"operation_name"},
        "match_when": {"operation_name_in": ["KeyDelete", "VaultDelete"]},
        "fp": ["Key rotation cleanup (paired with KeyCreate within 24h)"],
        "playbook": "tpl-data-destruction",
        "positive": {"operation_name": "KeyDelete", "key_name": "prod-encrypt", "principal": "user@corp.com"},
        "negative": {"operation_name": "KeyGet", "key_name": "prod-encrypt", "principal": "user@corp.com"},
    },
    {
        "slug": "azure-nsg-allow-all-inbound",
        "name": "Azure NSG Rule Allowing 0.0.0.0/0 Inbound",
        "severity": "high",
        "mitre": ["t1190"],
        "log_source": {"product": "azure", "service": "activity"},
        "fields": {"operation_name", "rule_source", "rule_destination_port"},
        "match_when": {"operation_name": "Microsoft.Network/networkSecurityGroups/securityRules/write", "rule_source": "*", "rule_destination_port_in": [22, 3389, 1433, 3306, 6379]},
        "fp": ["Public load balancer subnet (tag = role:public-lb)"],
        "playbook": "tpl-cloud-misconfig",
        "positive": {"operation_name": "Microsoft.Network/networkSecurityGroups/securityRules/write", "rule_source": "*", "rule_destination_port": 3389, "nsg": "prod-db"},
        "negative": {"operation_name": "Microsoft.Network/networkSecurityGroups/securityRules/write", "rule_source": "10.0.0.0/8", "rule_destination_port": 3389, "nsg": "prod-db"},
    },
    {
        "slug": "azure-storage-public-blob",
        "name": "Azure Storage Account Container Made Public",
        "severity": "high",
        "mitre": ["t1530"],
        "log_source": {"product": "azure", "service": "activity"},
        "fields": {"operation_name", "public_access"},
        "match_when": {"operation_name": "Microsoft.Storage/storageAccounts/blobServices/containers/write", "public_access_in": ["blob", "container"]},
        "fp": ["Static website hosting (purpose=public tag required)"],
        "playbook": "tpl-data-exposure",
        "positive": {"operation_name": "Microsoft.Storage/storageAccounts/blobServices/containers/write", "public_access": "container", "container": "customer-data"},
        "negative": {"operation_name": "Microsoft.Storage/storageAccounts/blobServices/containers/write", "public_access": "none", "container": "customer-data"},
    },
    {
        "slug": "azure-ad-mfa-disabled-for-user",
        "name": "Azure AD MFA Disabled for User",
        "severity": "high",
        "mitre": ["t1556.006"],
        "log_source": {"product": "azure", "service": "azuread-audit"},
        "fields": {"operation_name"},
        "match_when": {"operation_name": "Disable Strong Authentication"},
        "fp": ["Account migration to passkey-only (purpose=passkey tag required)"],
        "playbook": "tpl-defense-evasion",
        "positive": {"operation_name": "Disable Strong Authentication", "target_user": "ceo@corp.com"},
        "negative": {"operation_name": "Enable Strong Authentication", "target_user": "ceo@corp.com"},
    },
    {
        "slug": "azure-app-registration-permissive-scope",
        "name": "Azure AD App Registration Granted Broad Graph Scope",
        "severity": "high",
        "mitre": ["t1098.001"],
        "log_source": {"product": "azure", "service": "azuread-audit"},
        "fields": {"operation_name", "scope"},
        "match_when": {"operation_name": "Add app role assignment to service principal", "scope_in": ["Mail.ReadWrite", "Files.ReadWrite.All", "Directory.ReadWrite.All", "User.ReadWrite.All"]},
        "fp": ["IT service-account onboarding (must be ticketed)"],
        "playbook": "tpl-privilege-escalation",
        "positive": {"operation_name": "Add app role assignment to service principal", "scope": "Directory.ReadWrite.All", "app": "thirdparty-import"},
        "negative": {"operation_name": "Add app role assignment to service principal", "scope": "User.Read", "app": "thirdparty-import"},
    },
    {
        "slug": "azure-login-anonymous-ip",
        "name": "Azure AD Login from Tor / Anonymous IP",
        "severity": "high",
        "mitre": ["t1078.004"],
        "log_source": {"product": "azure", "service": "azuread-signin"},
        "fields": {"risk_event_type"},
        "match_when": {"risk_event_type": "anonymizedIPAddress"},
        "fp": ["Researchers using Tor for testing (must be tagged research-account)"],
        "playbook": "tpl-account-compromise",
        "positive": {"risk_event_type": "anonymizedIPAddress", "user": "ceo@corp.com", "src_ip": "185.220.101.5"},
        "negative": {"risk_event_type": "atypicalTravel", "user": "ceo@corp.com", "src_ip": "98.97.96.95"},
    },
    {
        "slug": "azure-resource-mass-delete",
        "name": "Azure Resource Mass Deletion",
        "severity": "critical",
        "mitre": ["t1485"],
        "log_source": {"product": "azure", "service": "activity"},
        "fields": {"operation_name", "delete_count_per_principal", "time_window_minutes"},
        "match_when": {"operation_name_endswith": "/delete", "delete_count_per_principal_gt": 50, "time_window_minutes_lt": 15},
        "fp": ["Sandbox cleanup (must originate from automation principal)"],
        "playbook": "tpl-data-destruction",
        "positive": {"operation_name": "Microsoft.Storage/storageAccounts/delete", "delete_count_per_principal": 120, "time_window_minutes": 5, "principal": "user@corp.com"},
        "negative": {"operation_name": "Microsoft.Storage/storageAccounts/delete", "delete_count_per_principal": 2, "time_window_minutes": 60, "principal": "user@corp.com"},
    },
    # GCP (10)
    {
        "slug": "gcp-iam-primitive-role-grant",
        "name": "GCP IAM Primitive Role (Owner/Editor) Granted",
        "severity": "high",
        "mitre": ["t1078.004"],
        "log_source": {"product": "gcp", "service": "audit"},
        "fields": {"method_name", "role"},
        "match_when": {"method_name": "SetIamPolicy", "role_in": ["roles/owner", "roles/editor"]},
        "fp": ["Initial bootstrap (one-time, ticketed)"],
        "playbook": "tpl-privilege-escalation",
        "positive": {"method_name": "SetIamPolicy", "role": "roles/owner", "principal": "user@corp.com", "project": "prod"},
        "negative": {"method_name": "SetIamPolicy", "role": "roles/storage.objectViewer", "principal": "user@corp.com", "project": "prod"},
    },
    {
        "slug": "gcp-service-account-key-created",
        "name": "GCP Service Account Key Created",
        "severity": "high",
        "mitre": ["t1098.001"],
        "log_source": {"product": "gcp", "service": "audit"},
        "fields": {"method_name"},
        "match_when": {"method_name": "google.iam.admin.v1.CreateServiceAccountKey"},
        "fp": ["IaC tooling using key-pair auth (must be tagged purpose=iac)"],
        "playbook": "tpl-privilege-escalation",
        "positive": {"method_name": "google.iam.admin.v1.CreateServiceAccountKey", "sa_email": "deploy@prod.iam.gserviceaccount.com"},
        "negative": {"method_name": "google.iam.admin.v1.UpdateServiceAccount", "sa_email": "deploy@prod.iam.gserviceaccount.com"},
    },
    {
        "slug": "gcp-gcs-bucket-public",
        "name": "GCP GCS Bucket Set to Public",
        "severity": "high",
        "mitre": ["t1530"],
        "log_source": {"product": "gcp", "service": "audit"},
        "fields": {"method_name", "iam_member"},
        "match_when": {"method_name": "storage.setIamPermissions", "iam_member_in": ["allUsers", "allAuthenticatedUsers"]},
        "fp": ["Public website hosting (must be tagged purpose=public)"],
        "playbook": "tpl-data-exposure",
        "positive": {"method_name": "storage.setIamPermissions", "iam_member": "allUsers", "bucket": "customer-data"},
        "negative": {"method_name": "storage.setIamPermissions", "iam_member": "user:dev@corp.com", "bucket": "customer-data"},
    },
    {
        "slug": "gcp-firewall-rule-allow-all",
        "name": "GCP Firewall Rule Allowing 0.0.0.0/0 Inbound",
        "severity": "high",
        "mitre": ["t1190"],
        "log_source": {"product": "gcp", "service": "audit"},
        "fields": {"method_name", "source_range", "ports"},
        "match_when": {"method_name": "compute.firewalls.insert", "source_range": "0.0.0.0/0", "port_in": [22, 3389, 5432, 3306, 6379]},
        "fp": ["External load balancer subnet (tagged role=public-lb)"],
        "playbook": "tpl-cloud-misconfig",
        "positive": {"method_name": "compute.firewalls.insert", "source_range": "0.0.0.0/0", "port": 22, "fw": "prod-bastion"},
        "negative": {"method_name": "compute.firewalls.insert", "source_range": "10.0.0.0/8", "port": 22, "fw": "prod-bastion"},
    },
    {
        "slug": "gcp-project-deletion",
        "name": "GCP Project Marked for Deletion",
        "severity": "critical",
        "mitre": ["t1485"],
        "log_source": {"product": "gcp", "service": "audit"},
        "fields": {"method_name"},
        "match_when": {"method_name": "DeleteProject"},
        "fp": ["Sandbox project cleanup (project name must contain -sbx or -test)"],
        "playbook": "tpl-data-destruction",
        "positive": {"method_name": "DeleteProject", "project": "prod-revenue", "principal": "user@corp.com"},
        "negative": {"method_name": "UndeleteProject", "project": "prod-revenue", "principal": "user@corp.com"},
    },
    {
        "slug": "gcp-audit-log-sink-disabled",
        "name": "GCP Audit Log Sink Disabled or Deleted",
        "severity": "critical",
        "mitre": ["t1562.008"],
        "log_source": {"product": "gcp", "service": "audit"},
        "fields": {"method_name"},
        "match_when": {"method_name_in": ["google.logging.v2.ConfigServiceV2.DeleteSink", "google.logging.v2.ConfigServiceV2.UpdateSink"]},
        "fp": ["Sink migration (must reference replacement sink)"],
        "playbook": "tpl-defense-evasion",
        "positive": {"method_name": "google.logging.v2.ConfigServiceV2.DeleteSink", "sink": "org-default", "principal": "user@corp.com"},
        "negative": {"method_name": "google.logging.v2.ConfigServiceV2.CreateSink", "sink": "org-default", "principal": "user@corp.com"},
    },
    {
        "slug": "gcp-org-policy-modified",
        "name": "GCP Organization Policy Modified",
        "severity": "high",
        "mitre": ["t1562.008"],
        "log_source": {"product": "gcp", "service": "audit"},
        "fields": {"method_name"},
        "match_when": {"method_name_endswith": ".SetOrgPolicy"},
        "fp": ["Approved policy change (must reference change ticket in metadata)"],
        "playbook": "tpl-defense-evasion",
        "positive": {"method_name": "google.cloud.orgpolicy.v2.OrgPolicy.SetOrgPolicy", "policy": "compute.requireOsLogin", "principal": "user@corp.com"},
        "negative": {"method_name": "google.cloud.orgpolicy.v2.OrgPolicy.GetEffectivePolicy", "policy": "compute.requireOsLogin", "principal": "user@corp.com"},
    },
    {
        "slug": "gcp-service-account-impersonation",
        "name": "GCP Service Account Impersonation Outside Allowlist",
        "severity": "high",
        "mitre": ["t1078.004"],
        "log_source": {"product": "gcp", "service": "audit"},
        "fields": {"method_name", "impersonator", "target_sa"},
        "match_when": {"method_name": "GenerateAccessToken", "impersonator_in_allowlist": False},
        "fp": ["IT support break-glass (allowlisted impersonator only)"],
        "playbook": "tpl-cloud-anomaly",
        "positive": {"method_name": "GenerateAccessToken", "impersonator": "intern@corp.com", "target_sa": "deploy@prod.iam.gserviceaccount.com", "impersonator_in_allowlist": False},
        "negative": {"method_name": "GenerateAccessToken", "impersonator": "deploy-bot@corp.com", "target_sa": "deploy@prod.iam.gserviceaccount.com", "impersonator_in_allowlist": True},
    },
    {
        "slug": "gcp-secret-manager-mass-export",
        "name": "GCP Secret Manager Mass AccessSecretVersion",
        "severity": "critical",
        "mitre": ["t1555.005", "t1530"],
        "log_source": {"product": "gcp", "service": "audit"},
        "fields": {"method_name", "secret_count_per_principal", "time_window_minutes"},
        "match_when": {"method_name": "google.cloud.secretmanager.v1.SecretManagerService.AccessSecretVersion", "secret_count_per_principal_gt": 25, "time_window_minutes_lt": 10},
        "fp": ["Boot of large microservice fleet (must be a known service principal in allowlist)"],
        "playbook": "tpl-data-exfil",
        "positive": {"method_name": "google.cloud.secretmanager.v1.SecretManagerService.AccessSecretVersion", "secret_count_per_principal": 80, "time_window_minutes": 4, "principal": "user@corp.com"},
        "negative": {"method_name": "google.cloud.secretmanager.v1.SecretManagerService.AccessSecretVersion", "secret_count_per_principal": 3, "time_window_minutes": 30, "principal": "deploy-bot@corp.com"},
    },
    {
        "slug": "gcp-bigquery-dataset-public",
        "name": "GCP BigQuery Dataset Made Public",
        "severity": "high",
        "mitre": ["t1530"],
        "log_source": {"product": "gcp", "service": "audit"},
        "fields": {"method_name", "iam_member"},
        "match_when": {"method_name": "google.cloud.bigquery.v2.DatasetService.UpdateDataset", "iam_member_in": ["allUsers", "allAuthenticatedUsers"]},
        "fp": ["Public datasets program (purpose=public tag required)"],
        "playbook": "tpl-data-exposure",
        "positive": {"method_name": "google.cloud.bigquery.v2.DatasetService.UpdateDataset", "iam_member": "allUsers", "dataset": "customer_metrics"},
        "negative": {"method_name": "google.cloud.bigquery.v2.DatasetService.UpdateDataset", "iam_member": "user:analyst@corp.com", "dataset": "customer_metrics"},
    },
    # Multi-cloud (5)
    {
        "slug": "cloud-secrets-in-env",
        "name": "Cloud Workload Spawned with Secrets in Environment Variables",
        "severity": "high",
        "mitre": ["t1552.001"],
        "log_source": {"product": "cloud", "service": "workload"},
        "fields": {"event_name", "env_has_secret"},
        "match_when": {"event_name_in": ["RunInstances", "RunPods", "DeployContainer"], "env_has_secret": True},
        "fp": ["Legacy workloads pre-migration to a secret-store (decommission ticket required)"],
        "playbook": "tpl-cloud-misconfig",
        "positive": {"event_name": "DeployContainer", "env_has_secret": True, "container": "billing-svc"},
        "negative": {"event_name": "DeployContainer", "env_has_secret": False, "container": "billing-svc"},
    },
    {
        "slug": "cloud-container-registry-public",
        "name": "Container Registry Repository Made Public",
        "severity": "medium",
        "mitre": ["t1525"],
        "log_source": {"product": "cloud", "service": "registry"},
        "fields": {"event_name", "visibility"},
        "match_when": {"event_name_in": ["UpdateRepositoryVisibility", "SetIamPolicy"], "visibility": "public"},
        "fp": ["Public OSS image publishing (purpose=public-oss tag required)"],
        "playbook": "tpl-data-exposure",
        "positive": {"event_name": "UpdateRepositoryVisibility", "visibility": "public", "repo": "internal-tooling"},
        "negative": {"event_name": "UpdateRepositoryVisibility", "visibility": "private", "repo": "internal-tooling"},
    },
    {
        "slug": "cloud-tfstate-public",
        "name": "Terraform State File Stored in Public Bucket",
        "severity": "critical",
        "mitre": ["t1530", "t1552.001"],
        "log_source": {"product": "cloud", "service": "storage"},
        "fields": {"object_path", "bucket_visibility"},
        "match_when": {"object_path_endswith": ".tfstate", "bucket_visibility": "public"},
        "fp": ["Demo/training repos (must be in dedicated demo project)"],
        "playbook": "tpl-data-exposure",
        "positive": {"object_path": "iac/prod/main.tfstate", "bucket_visibility": "public", "bucket": "ops-iac"},
        "negative": {"object_path": "iac/prod/main.tfstate", "bucket_visibility": "private", "bucket": "ops-iac"},
    },
    {
        "slug": "cloud-internet-load-balancer-no-waf",
        "name": "Internet-Facing Load Balancer Without WAF",
        "severity": "medium",
        "mitre": ["t1190"],
        "log_source": {"product": "cloud", "service": "lb"},
        "fields": {"event_name", "scheme", "waf_attached"},
        "match_when": {"event_name_in": ["CreateLoadBalancer", "ModifyLoadBalancerAttributes"], "scheme": "internet-facing", "waf_attached": False},
        "fp": ["Health-check / status-page endpoints (must be tagged purpose=status)"],
        "playbook": "tpl-cloud-misconfig",
        "positive": {"event_name": "CreateLoadBalancer", "scheme": "internet-facing", "waf_attached": False, "lb": "prod-api"},
        "negative": {"event_name": "CreateLoadBalancer", "scheme": "internet-facing", "waf_attached": True, "lb": "prod-api"},
    },
    {
        "slug": "cloud-cross-account-trust-add",
        "name": "Cross-Account Trust Added to Privileged Role",
        "severity": "critical",
        "mitre": ["t1199"],
        "log_source": {"product": "cloud", "service": "iam"},
        "fields": {"event_name", "trusted_principal_external_account", "external_account_in_allowlist"},
        "match_when": {"event_name_in": ["UpdateAssumeRolePolicy", "PutRolePolicy"], "trusted_principal_external_account": True, "external_account_in_allowlist": False},
        "fp": ["Approved partner SaaS integration (allowlist required)"],
        "playbook": "tpl-cloud-anomaly",
        "positive": {"event_name": "UpdateAssumeRolePolicy", "trusted_principal_external_account": True, "external_account_in_allowlist": False, "role": "prod-admin"},
        "negative": {"event_name": "UpdateAssumeRolePolicy", "trusted_principal_external_account": False, "external_account_in_allowlist": True, "role": "prod-admin"},
    },
]

# =============================================================================
# IDENTITY (40)
# =============================================================================
IDENTITY: list[dict] = [
    # Authentication (15)
    {
        "slug": "brute-force-login",
        "name": "Authentication Brute-Force Burst",
        "description": "Detects high-frequency failed authentication attempts against a single account, which is a classic indicator of credential-stuffing or password-spraying attempts. Threshold is intentionally conservative to reduce noise.",
        "severity": "high",
        "mitre": ["t1110.001"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "outcome", "fail_count", "time_window_minutes"},
        "match_when": {"event_type": "user.session.start", "outcome": "FAILURE", "fail_count_gt": 20, "time_window_minutes_lt": 10},
        "fp": ["Misconfigured client looping forever (rare; tag known cases)"],
        "playbook": "tpl-account-compromise",
        "positive": {"event_type": "user.session.start", "outcome": "FAILURE", "fail_count": 80, "time_window_minutes": 5, "user": "ceo@corp.com"},
        "negative": {"event_type": "user.session.start", "outcome": "FAILURE", "fail_count": 2, "time_window_minutes": 30, "user": "ceo@corp.com"},
    },
    {
        "slug": "impossible-travel",
        "name": "Impossible Travel Between Two Authentications",
        "description": "Detects two successful authentication events for the same user from geographically distant locations within a time window that would require travel speeds exceeding 800 km/h. Strong indicator of compromised credentials being shared between attacker and legitimate user.",
        "severity": "high",
        "mitre": ["t1078"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "outcome", "travel_speed_kmh", "time_delta_minutes"},
        "match_when": {"event_type": "user.session.start", "outcome": "SUCCESS", "travel_speed_kmh_gt": 800, "time_delta_minutes_lt": 120},
        "fp": ["VPN usage that changes apparent geolocation", "Tor / proxy services"],
        "playbook": "tpl-account-compromise",
        "positive": {"event_type": "user.session.start", "outcome": "SUCCESS", "travel_speed_kmh": 1100, "time_delta_minutes": 30, "user": "vp@corp.com"},
        "negative": {"event_type": "user.session.start", "outcome": "SUCCESS", "travel_speed_kmh": 12, "time_delta_minutes": 240, "user": "vp@corp.com"},
    },
    {
        "slug": "password-spray",
        "name": "Password Spray Across Many Users from Single IP",
        "severity": "high",
        "mitre": ["t1110.003"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "outcome", "distinct_users_per_ip", "time_window_minutes"},
        "match_when": {"event_type": "user.session.start", "outcome": "FAILURE", "distinct_users_per_ip_gt": 30, "time_window_minutes_lt": 30},
        "fp": ["Penetration tests (must be ticketed)"],
        "playbook": "tpl-account-compromise",
        "positive": {"event_type": "user.session.start", "outcome": "FAILURE", "distinct_users_per_ip": 60, "time_window_minutes": 12, "src_ip": "203.0.113.7"},
        "negative": {"event_type": "user.session.start", "outcome": "FAILURE", "distinct_users_per_ip": 1, "time_window_minutes": 60, "src_ip": "10.0.0.5"},
    },
    {
        "slug": "login-anonymous-ip",
        "name": "Login from Tor / Anonymous Proxy",
        "severity": "high",
        "mitre": ["t1078"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "ip_anonymizer"},
        "match_when": {"event_type": "user.session.start", "ip_anonymizer": True},
        "fp": ["Researchers / red team (tagged research-account)"],
        "playbook": "tpl-account-compromise",
        "positive": {"event_type": "user.session.start", "ip_anonymizer": True, "user": "ceo@corp.com"},
        "negative": {"event_type": "user.session.start", "ip_anonymizer": False, "user": "ceo@corp.com"},
    },
    {
        "slug": "login-outside-business-hours",
        "name": "Privileged Login Outside Business Hours",
        "severity": "medium",
        "mitre": ["t1078"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "outcome", "user_role", "hour_of_day_local"},
        "match_when": {"event_type": "user.session.start", "outcome": "SUCCESS", "user_role_in": ["admin", "privileged"], "hour_of_day_local_not_in": list(range(7, 20))},
        "fp": ["On-call rotation outside hours (must be on-call)", "Travel by privileged user (tag travel)"],
        "playbook": "tpl-account-anomaly",
        "positive": {"event_type": "user.session.start", "outcome": "SUCCESS", "user_role": "admin", "hour_of_day_local": 3, "user": "admin@corp.com"},
        "negative": {"event_type": "user.session.start", "outcome": "SUCCESS", "user_role": "admin", "hour_of_day_local": 10, "user": "admin@corp.com"},
    },
    {
        "slug": "login-from-foreign-country",
        "name": "Login from Country Outside Allowed Geography",
        "severity": "high",
        "mitre": ["t1078"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "outcome", "src_country", "user_country_allowlist"},
        "match_when": {"event_type": "user.session.start", "outcome": "SUCCESS", "src_country_not_in_allowlist": True},
        "fp": ["Approved business travel (must be tagged)"],
        "playbook": "tpl-account-compromise",
        "positive": {"event_type": "user.session.start", "outcome": "SUCCESS", "src_country": "RU", "src_country_not_in_allowlist": True, "user": "user@corp.com"},
        "negative": {"event_type": "user.session.start", "outcome": "SUCCESS", "src_country": "US", "src_country_not_in_allowlist": False, "user": "user@corp.com"},
    },
    {
        "slug": "disabled-account-login-attempt",
        "name": "Authentication Attempt Against Disabled Account",
        "severity": "medium",
        "mitre": ["t1078"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "user_state"},
        "match_when": {"event_type": "user.session.start", "user_state_in": ["DISABLED", "DEPROVISIONED"]},
        "fp": ["Lingering background jobs after offboarding (rare; transient)"],
        "playbook": "tpl-account-anomaly",
        "positive": {"event_type": "user.session.start", "user_state": "DISABLED", "user": "former-employee@corp.com"},
        "negative": {"event_type": "user.session.start", "user_state": "ACTIVE", "user": "former-employee@corp.com"},
    },
    {
        "slug": "mfa-fatigue",
        "name": "MFA Push Bombing (MFA Fatigue)",
        "severity": "high",
        "mitre": ["t1621"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "mfa_push_count", "time_window_minutes"},
        "match_when": {"event_type": "user.mfa.factor.push", "mfa_push_count_gt": 6, "time_window_minutes_lt": 5},
        "fp": ["User retrying after a missed prompt (typically 2-3 retries)"],
        "playbook": "tpl-account-compromise",
        "positive": {"event_type": "user.mfa.factor.push", "mfa_push_count": 25, "time_window_minutes": 3, "user": "vp@corp.com"},
        "negative": {"event_type": "user.mfa.factor.push", "mfa_push_count": 2, "time_window_minutes": 5, "user": "vp@corp.com"},
    },
    {
        "slug": "mfa-bypass-policy-change",
        "name": "MFA Requirement Removed from User Policy",
        "severity": "critical",
        "mitre": ["t1556.006"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "policy_change_field"},
        "match_when": {"event_type": "policy.lifecycle.update", "policy_change_field": "mfa_required:false"},
        "fp": ["Migration to passkey-only (must reference replacement policy)"],
        "playbook": "tpl-defense-evasion",
        "positive": {"event_type": "policy.lifecycle.update", "policy_change_field": "mfa_required:false", "policy_name": "all-employees"},
        "negative": {"event_type": "policy.lifecycle.update", "policy_change_field": "session_timeout:8h", "policy_name": "all-employees"},
    },
    {
        "slug": "expired-credential-reuse",
        "name": "Authentication with Expired Credential",
        "severity": "medium",
        "mitre": ["t1110"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "credential_state"},
        "match_when": {"event_type": "user.session.start", "credential_state": "EXPIRED"},
        "fp": ["Cached credentials in legacy automation (rotation grace period)"],
        "playbook": "tpl-account-anomaly",
        "positive": {"event_type": "user.session.start", "credential_state": "EXPIRED", "user": "user@corp.com"},
        "negative": {"event_type": "user.session.start", "credential_state": "VALID", "user": "user@corp.com"},
    },
    {
        "slug": "service-account-interactive-login",
        "name": "Service Account Used for Interactive Login",
        "severity": "high",
        "mitre": ["t1078.004"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "user_type", "session_type"},
        "match_when": {"event_type": "user.session.start", "user_type": "service_account", "session_type": "interactive"},
        "fp": ["Service account testing during onboarding (must be ticketed)"],
        "playbook": "tpl-account-compromise",
        "positive": {"event_type": "user.session.start", "user_type": "service_account", "session_type": "interactive", "user": "deploy-bot"},
        "negative": {"event_type": "user.session.start", "user_type": "service_account", "session_type": "machine", "user": "deploy-bot"},
    },
    {
        "slug": "root-ssh-login",
        "name": "Root SSH Login on Production Host",
        "severity": "high",
        "mitre": ["t1078.001"],
        "log_source": {"product": "linux", "service": "auth"},
        "fields": {"event_type", "user", "host_role"},
        "match_when": {"event_type": "ssh-accept", "user": "root", "host_role": "production"},
        "fp": ["Disaster recovery break-glass (must be ticketed)"],
        "playbook": "tpl-privilege-escalation",
        "positive": {"event_type": "ssh-accept", "user": "root", "host_role": "production", "host": "db-prod-01"},
        "negative": {"event_type": "ssh-accept", "user": "deploy", "host_role": "production", "host": "db-prod-01"},
    },
    {
        "slug": "default-credential-login",
        "name": "Login with Vendor Default Credentials",
        "severity": "high",
        "mitre": ["t1078.001"],
        "log_source": {"product": "linux", "service": "auth"},
        "fields": {"event_type", "user_in_default_list", "outcome"},
        "match_when": {"event_type": "ssh-accept", "user_in_default_list": True, "outcome": "SUCCESS"},
        "fp": ["Lab/sandbox hosts (must not be production-tagged)"],
        "playbook": "tpl-account-compromise",
        "positive": {"event_type": "ssh-accept", "user": "admin", "user_in_default_list": True, "outcome": "SUCCESS", "host": "appliance-01"},
        "negative": {"event_type": "ssh-accept", "user": "real-employee", "user_in_default_list": False, "outcome": "SUCCESS", "host": "appliance-01"},
    },
    {
        "slug": "shared-account-login-spike",
        "name": "Shared Account Login Spike (Distinct IPs)",
        "severity": "medium",
        "mitre": ["t1078"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "distinct_ip_count_per_user", "time_window_minutes"},
        "match_when": {"event_type": "user.session.start", "distinct_ip_count_per_user_gt": 5, "time_window_minutes_lt": 10},
        "fp": ["Shared corporate workstation (multi-user)"],
        "playbook": "tpl-account-anomaly",
        "positive": {"event_type": "user.session.start", "distinct_ip_count_per_user": 12, "time_window_minutes": 6, "user": "shared-account@corp.com"},
        "negative": {"event_type": "user.session.start", "distinct_ip_count_per_user": 1, "time_window_minutes": 60, "user": "user@corp.com"},
    },
    {
        "slug": "login-during-incident",
        "name": "Authentication During Active P0/P1 Incident Window",
        "severity": "medium",
        "mitre": ["t1078"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "outcome", "active_p0_or_p1_incident", "user_role"},
        "match_when": {"event_type": "user.session.start", "outcome": "SUCCESS", "active_p0_or_p1_incident": True, "user_role_not_in": ["incident_responder", "admin"]},
        "fp": ["IR team members not in the responder allowlist (rare; tag and continue)"],
        "playbook": "tpl-incident-anomaly",
        "positive": {"event_type": "user.session.start", "outcome": "SUCCESS", "active_p0_or_p1_incident": True, "user_role": "marketing", "user": "user@corp.com"},
        "negative": {"event_type": "user.session.start", "outcome": "SUCCESS", "active_p0_or_p1_incident": False, "user_role": "marketing", "user": "user@corp.com"},
    },
    # Authorization (10)
    {
        "slug": "privileged-role-assignment",
        "name": "Privileged Role Assignment",
        "severity": "high",
        "mitre": ["t1098"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "role_name"},
        "match_when": {"event_type": "user.role.add", "role_name_in": ["admin", "owner", "global_admin"]},
        "fp": ["Quarterly access review (ticketed)"],
        "playbook": "tpl-privilege-escalation",
        "positive": {"event_type": "user.role.add", "role_name": "admin", "target_user": "user@corp.com"},
        "negative": {"event_type": "user.role.add", "role_name": "viewer", "target_user": "user@corp.com"},
    },
    {
        "slug": "jit-elevation-abuse",
        "name": "Just-In-Time Elevation Held Beyond Window",
        "severity": "medium",
        "mitre": ["t1078"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "elevation_duration_minutes"},
        "match_when": {"event_type": "user.privilege.elevate", "elevation_duration_minutes_gt": 240},
        "fp": ["Maintenance window approved beyond 4h (must be ticketed)"],
        "playbook": "tpl-account-anomaly",
        "positive": {"event_type": "user.privilege.elevate", "elevation_duration_minutes": 720, "user": "user@corp.com"},
        "negative": {"event_type": "user.privilege.elevate", "elevation_duration_minutes": 60, "user": "user@corp.com"},
    },
    {
        "slug": "sudo-no-mfa",
        "name": "Sudo Used Without MFA",
        "severity": "high",
        "mitre": ["t1548.003"],
        "log_source": {"product": "linux", "service": "sudo"},
        "fields": {"event_type", "mfa_verified"},
        "match_when": {"event_type": "sudo-use", "mfa_verified": False},
        "fp": ["Hosts pending MFA rollout (host_role=legacy tag required)"],
        "playbook": "tpl-privilege-escalation",
        "positive": {"event_type": "sudo-use", "mfa_verified": False, "host": "db-prod-01", "user": "user"},
        "negative": {"event_type": "sudo-use", "mfa_verified": True, "host": "db-prod-01", "user": "user"},
    },
    {
        "slug": "group-policy-modification",
        "name": "Active Directory Group Policy Modified",
        "severity": "high",
        "mitre": ["t1484.001"],
        "log_source": {"product": "windows", "service": "security"},
        "fields": {"event_id"},
        "match_when": {"event_id_in": [5136, 5137, 5138, 5139]},
        "fp": ["Change-management approved GPO updates (ticket reference required)"],
        "playbook": "tpl-defense-evasion",
        "positive": {"event_id": 5136, "object_class": "groupPolicyContainer", "user": "user@corp.com"},
        "negative": {"event_id": 4624, "user": "user@corp.com"},
    },
    {
        "slug": "rbac-cluster-admin-binding",
        "name": "Kubernetes ClusterRoleBinding to cluster-admin",
        "severity": "critical",
        "mitre": ["t1078.004"],
        "log_source": {"product": "kubernetes", "service": "audit"},
        "fields": {"verb", "object_resource", "role_ref"},
        "match_when": {"verb": "create", "object_resource": "clusterrolebindings", "role_ref": "cluster-admin"},
        "fp": ["Initial cluster bootstrap (one-time)"],
        "playbook": "tpl-privilege-escalation",
        "positive": {"verb": "create", "object_resource": "clusterrolebindings", "role_ref": "cluster-admin", "subject": "user@corp.com"},
        "negative": {"verb": "create", "object_resource": "clusterrolebindings", "role_ref": "view", "subject": "user@corp.com"},
    },
    {
        "slug": "iam-policy-detach-defense",
        "name": "Defensive IAM Policy Detached",
        "severity": "critical",
        "mitre": ["t1562.008"],
        "log_source": {"product": "aws", "service": "cloudtrail"},
        "fields": {"event_name", "policy_name"},
        "match_when": {"event_name_in": ["DetachUserPolicy", "DetachRolePolicy"], "policy_name_contains_any": ["DefaultDeny", "GuardrailDeny", "OrgDeny"]},
        "fp": ["Policy migration during Org SCP refactor (ticket required)"],
        "playbook": "tpl-defense-evasion",
        "positive": {"event_name": "DetachRolePolicy", "policy_name": "OrgDenyDeleteCloudTrail", "role": "deploy-bot"},
        "negative": {"event_name": "DetachRolePolicy", "policy_name": "ReadOnlyAccess", "role": "deploy-bot"},
    },
    {
        "slug": "domain-password-policy-weakened",
        "name": "Domain Password Policy Weakened",
        "severity": "high",
        "mitre": ["t1556"],
        "log_source": {"product": "windows", "service": "security"},
        "fields": {"event_id", "policy_change"},
        "match_when": {"event_id_in": [4739, 4738], "policy_change_in": ["min-length-decreased", "complexity-disabled", "lockout-disabled"]},
        "fp": ["Approved policy refactor (ticketed, paired with rotation)"],
        "playbook": "tpl-defense-evasion",
        "positive": {"event_id": 4739, "policy_change": "complexity-disabled", "user": "user@corp.com"},
        "negative": {"event_id": 4739, "policy_change": "min-length-increased", "user": "user@corp.com"},
    },
    {
        "slug": "oauth-broad-scope-grant",
        "name": "OAuth App Granted Broad Scopes by User",
        "severity": "high",
        "mitre": ["t1098.001"],
        "log_source": {"product": "google-workspace", "service": "audit"},
        "fields": {"event_type", "scope_set"},
        "match_when": {"event_type": "oauth.token.grant", "scope_set_contains_any": ["mail.readwrite", "drive.full", "admin.directory"]},
        "fp": ["IT-managed integrations (publisher in allowlist)"],
        "playbook": "tpl-account-compromise",
        "positive": {"event_type": "oauth.token.grant", "scope_set": ["drive.full"], "user": "user@corp.com", "app": "thirdparty-importer"},
        "negative": {"event_type": "oauth.token.grant", "scope_set": ["calendar.read"], "user": "user@corp.com", "app": "thirdparty-importer"},
    },
    {
        "slug": "app-token-broad-default",
        "name": "GitHub App Installed with Repo Admin Permission",
        "severity": "high",
        "mitre": ["t1098.001"],
        "log_source": {"product": "github", "service": "audit"},
        "fields": {"action", "permission_administration"},
        "match_when": {"action": "integration_installation.create", "permission_administration": "write"},
        "fp": ["GitHub Apps from approved-publisher list"],
        "playbook": "tpl-supply-chain",
        "positive": {"action": "integration_installation.create", "permission_administration": "write", "app": "thirdparty-bot"},
        "negative": {"action": "integration_installation.create", "permission_administration": "read", "app": "thirdparty-bot"},
    },
    {
        "slug": "token-reuse-new-device",
        "name": "Persistent Session Token Reused from New Device Fingerprint",
        "severity": "high",
        "mitre": ["t1550.004"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "device_fingerprint_seen_before", "session_age_hours"},
        "match_when": {"event_type": "user.session.access_token", "device_fingerprint_seen_before": False, "session_age_hours_gt": 8},
        "fp": ["Browser update changing fingerprint (must be paired with consistent IP)"],
        "playbook": "tpl-account-compromise",
        "positive": {"event_type": "user.session.access_token", "device_fingerprint_seen_before": False, "session_age_hours": 24, "user": "ceo@corp.com"},
        "negative": {"event_type": "user.session.access_token", "device_fingerprint_seen_before": True, "session_age_hours": 24, "user": "ceo@corp.com"},
    },
    # Account lifecycle (10)
    {
        "slug": "account-creation-by-non-admin",
        "name": "User Account Creation by Non-Admin Principal",
        "severity": "high",
        "mitre": ["t1136.001"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "actor_role"},
        "match_when": {"event_type": "user.lifecycle.create", "actor_role_not_in": ["admin", "user_admin"]},
        "fp": ["Self-service guest invite (must require sponsor)"],
        "playbook": "tpl-privilege-escalation",
        "positive": {"event_type": "user.lifecycle.create", "actor_role": "engineer", "actor": "user@corp.com"},
        "negative": {"event_type": "user.lifecycle.create", "actor_role": "admin", "actor": "admin@corp.com"},
    },
    {
        "slug": "admin-account-deletion",
        "name": "Privileged Account Deleted",
        "severity": "critical",
        "mitre": ["t1531"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "target_user_role"},
        "match_when": {"event_type": "user.lifecycle.deactivate", "target_user_role_in": ["admin", "owner"]},
        "fp": ["Offboarding (must reference HR ticket)"],
        "playbook": "tpl-account-compromise",
        "positive": {"event_type": "user.lifecycle.deactivate", "target_user_role": "admin", "target_user": "ceo@corp.com"},
        "negative": {"event_type": "user.lifecycle.deactivate", "target_user_role": "viewer", "target_user": "user@corp.com"},
    },
    {
        "slug": "account-enable-after-disable",
        "name": "Disabled Account Re-enabled",
        "severity": "high",
        "mitre": ["t1098"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "previous_state"},
        "match_when": {"event_type": "user.lifecycle.activate", "previous_state": "DISABLED"},
        "fp": ["Re-hire (must reference HR ticket)"],
        "playbook": "tpl-account-anomaly",
        "positive": {"event_type": "user.lifecycle.activate", "previous_state": "DISABLED", "user": "former-employee@corp.com"},
        "negative": {"event_type": "user.lifecycle.activate", "previous_state": "STAGED", "user": "new-hire@corp.com"},
    },
    {
        "slug": "self-password-reset-admin",
        "name": "Admin Password Reset Initiated by Self via Self-Service",
        "severity": "medium",
        "mitre": ["t1098"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "reset_method", "user_role"},
        "match_when": {"event_type": "user.account.reset_password", "reset_method": "self-service", "user_role": "admin"},
        "fp": ["Forgotten-password flow with strong second factor (rare for admins)"],
        "playbook": "tpl-account-anomaly",
        "positive": {"event_type": "user.account.reset_password", "reset_method": "self-service", "user_role": "admin", "user": "admin@corp.com"},
        "negative": {"event_type": "user.account.reset_password", "reset_method": "helpdesk-assisted", "user_role": "admin", "user": "admin@corp.com"},
    },
    {
        "slug": "password-reset-out-of-hours",
        "name": "Password Reset Out of Business Hours for Privileged Account",
        "severity": "medium",
        "mitre": ["t1098"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "user_role", "hour_of_day_local"},
        "match_when": {"event_type": "user.account.reset_password", "user_role_in": ["admin", "privileged"], "hour_of_day_local_not_in": list(range(7, 20))},
        "fp": ["On-call out-of-hours legitimate reset (must be on-call rotation)"],
        "playbook": "tpl-account-anomaly",
        "positive": {"event_type": "user.account.reset_password", "user_role": "admin", "hour_of_day_local": 2, "user": "admin@corp.com"},
        "negative": {"event_type": "user.account.reset_password", "user_role": "admin", "hour_of_day_local": 11, "user": "admin@corp.com"},
    },
    {
        "slug": "ad-replication-non-dc",
        "name": "Active Directory Replication Request from Non-Domain-Controller",
        "severity": "critical",
        "mitre": ["t1003.006"],
        "log_source": {"product": "windows", "service": "security"},
        "fields": {"event_id", "source_role"},
        "match_when": {"event_id": 4662, "operation_type_contains": "DS-Replication-Get-Changes", "source_role_not_in": ["domain_controller"]},
        "fp": ["Approved replication agents (azure ad connect; explicit allowlist)"],
        "playbook": "tpl-credential-theft",
        "positive": {"event_id": 4662, "operation_type": "DS-Replication-Get-Changes-All", "source_role": "workstation", "user": "user@corp.com"},
        "negative": {"event_id": 4662, "operation_type": "DS-Replication-Get-Changes-All", "source_role": "domain_controller", "user": "DC01$"},
    },
    {
        "slug": "kerberoasting",
        "name": "Kerberoasting (Service-Ticket Request for SPN)",
        "severity": "high",
        "mitre": ["t1558.003"],
        "log_source": {"product": "windows", "service": "security"},
        "fields": {"event_id", "ticket_encryption", "spn_count_per_user", "time_window_minutes"},
        "match_when": {"event_id": 4769, "ticket_encryption_in": ["RC4-HMAC", "0x17"], "spn_count_per_user_gt": 5, "time_window_minutes_lt": 5},
        "fp": ["Legacy services that still issue RC4 tickets (host_role=legacy tag)"],
        "playbook": "tpl-credential-theft",
        "positive": {"event_id": 4769, "ticket_encryption": "RC4-HMAC", "spn_count_per_user": 12, "time_window_minutes": 2, "user": "user@corp.com"},
        "negative": {"event_id": 4769, "ticket_encryption": "AES256-CTS-HMAC-SHA1-96", "spn_count_per_user": 1, "time_window_minutes": 60, "user": "user@corp.com"},
    },
    {
        "slug": "asreproasting",
        "name": "AS-REP Roasting (Account with Pre-Auth Disabled)",
        "severity": "high",
        "mitre": ["t1558.004"],
        "log_source": {"product": "windows", "service": "security"},
        "fields": {"event_id", "preauth_required"},
        "match_when": {"event_id": 4768, "preauth_required": False},
        "fp": ["Legacy unix/krb5-style accounts with explicit allowlist"],
        "playbook": "tpl-credential-theft",
        "positive": {"event_id": 4768, "preauth_required": False, "user": "service-legacy"},
        "negative": {"event_id": 4768, "preauth_required": True, "user": "user@corp.com"},
    },
    {
        "slug": "golden-ticket",
        "name": "Golden Ticket Indicator (Anomalous TGT Lifetime)",
        "severity": "critical",
        "mitre": ["t1558.001"],
        "log_source": {"product": "windows", "service": "security"},
        "fields": {"event_id", "ticket_lifetime_hours"},
        "match_when": {"event_id": 4624, "logon_type": 3, "ticket_lifetime_hours_gt": 24},
        "fp": ["Forest-trust kerberos tickets (rare; allowlist trust)"],
        "playbook": "tpl-credential-theft",
        "positive": {"event_id": 4624, "logon_type": 3, "ticket_lifetime_hours": 720, "user": "user@corp.com"},
        "negative": {"event_id": 4624, "logon_type": 3, "ticket_lifetime_hours": 8, "user": "user@corp.com"},
    },
    {
        "slug": "silver-ticket",
        "name": "Silver Ticket Indicator (Service Ticket Without TGS Hit)",
        "severity": "critical",
        "mitre": ["t1558.002"],
        "log_source": {"product": "windows", "service": "security"},
        "fields": {"event_id", "tgs_event_seen"},
        "match_when": {"event_id": 4624, "logon_type": 3, "tgs_event_seen": False},
        "fp": ["Cached TGT reuse outside log retention window"],
        "playbook": "tpl-credential-theft",
        "positive": {"event_id": 4624, "logon_type": 3, "tgs_event_seen": False, "user": "service-account"},
        "negative": {"event_id": 4624, "logon_type": 3, "tgs_event_seen": True, "user": "service-account"},
    },
    # SSO/Federation (5)
    {
        "slug": "saml-response-anomaly",
        "name": "SAML Response with Mismatched Issuer or Future-Dated NotBefore",
        "severity": "critical",
        "mitre": ["t1606.002"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type", "issuer_valid", "notbefore_in_future"},
        "match_when": {"event_type": "user.authentication.sso", "any_of": [{"issuer_valid": False}, {"notbefore_in_future": True}]},
        "fp": ["Clock-skew between IDP and SP (rare; <2min)"],
        "playbook": "tpl-credential-theft",
        "positive": {"event_type": "user.authentication.sso", "issuer_valid": False, "notbefore_in_future": False, "user": "user@corp.com"},
        "negative": {"event_type": "user.authentication.sso", "issuer_valid": True, "notbefore_in_future": False, "user": "user@corp.com"},
    },
    {
        "slug": "federated-trust-modified",
        "name": "Federation Trust Relationship Modified",
        "severity": "critical",
        "mitre": ["t1556.007"],
        "log_source": {"product": "azure", "service": "azuread-audit"},
        "fields": {"operation_name"},
        "match_when": {"operation_name_in": ["Set domain authentication", "Set federation settings on domain"]},
        "fp": ["Approved federation cutover (must reference change ticket)"],
        "playbook": "tpl-defense-evasion",
        "positive": {"operation_name": "Set domain authentication", "domain": "corp.com"},
        "negative": {"operation_name": "Verify domain", "domain": "corp.com"},
    },
    {
        "slug": "idp-metadata-changed",
        "name": "IDP Metadata or Signing Cert Changed",
        "severity": "critical",
        "mitre": ["t1556"],
        "log_source": {"product": "okta", "service": "system-log"},
        "fields": {"event_type"},
        "match_when": {"event_type_in": ["app.idp.update_signing_certificate", "app.idp.update_metadata"]},
        "fp": ["Cert rotation (must be paired with rotation calendar)"],
        "playbook": "tpl-defense-evasion",
        "positive": {"event_type": "app.idp.update_signing_certificate", "app": "salesforce"},
        "negative": {"event_type": "app.idp.lifecycle.activate", "app": "salesforce"},
    },
    {
        "slug": "ca-policy-scope-broadened",
        "name": "Conditional Access Policy Scope Broadened (Less Restrictive)",
        "severity": "high",
        "mitre": ["t1562.001"],
        "log_source": {"product": "azure", "service": "azuread-audit"},
        "fields": {"operation_name", "policy_change"},
        "match_when": {"operation_name": "Update conditional access policy", "policy_change_in": ["scope-expanded", "exclusion-added"]},
        "fp": ["Onboarding new application to existing policy (ticketed)"],
        "playbook": "tpl-defense-evasion",
        "positive": {"operation_name": "Update conditional access policy", "policy_change": "exclusion-added", "policy_name": "MFA-required"},
        "negative": {"operation_name": "Update conditional access policy", "policy_change": "exclusion-removed", "policy_name": "MFA-required"},
    },
    {
        "slug": "federation-cross-tenant-access",
        "name": "Cross-Tenant Identity Access Granted",
        "severity": "high",
        "mitre": ["t1199"],
        "log_source": {"product": "azure", "service": "azuread-audit"},
        "fields": {"operation_name"},
        "match_when": {"operation_name": "Add cross-tenant access policy"},
        "fp": ["Approved B2B partnership (allowlisted partner-tenant)"],
        "playbook": "tpl-cloud-anomaly",
        "positive": {"operation_name": "Add cross-tenant access policy", "partner_tenant": "external-tenant-id"},
        "negative": {"operation_name": "Update cross-tenant access policy", "partner_tenant": "allowlisted-partner-tenant"},
    },
]

# fmt: on
