/**
 * Bundled deterministic demo alerts. Generated by `scripts/gen-fixtures.mjs`
 * and inlined at build time (tsup + resolveJsonModule) so `npx aisoc triage
 * --demo` needs zero network and zero credentials.
 */

import type { Alert } from "../verdict/types.js";
import demo from "./demo-alerts.json" with { type: "json" };

interface DemoFile {
  count: number;
  alerts: Alert[];
}

export function loadDemoAlerts(): Alert[] {
  return (demo as DemoFile).alerts;
}

export const DEMO_ALERT_COUNT = (demo as DemoFile).count;
